#!/usr/bin/env bash

#2.0 -- cuos.master
#3.0 -- cuos.202211
# make sure login docker registry
#docker login docker.clounix.com with your login password
#docker login registry.clounix.com with user/Clounix123

# check arguments
if [ $# -eq 0 ]; then
  echo "Usage: $0 [cuos.master | cuos.202211] <command>"
  exit 1
fi

bldver=$1
case "$bldver" in
  "cuos.master")
    bldver='2.0'
    ;;
  "cuos.202211")
    bldver='3.0'
    ;;
  *)
    echo "Unknown bldver: $bldver"
    echo "Use default 1.0"
    bldver='1.0'
    ;;
esac



# check docker image for building
if [ "$(docker images -q docker.clounix.com/software/platform/tools/nb-knet/build-env:$bldver 2> /dev/null)" == "" ]; then
  echo "Pull Docker image"
  docker pull docker.clounix.com/software/platform/tools/nb-knet/build-env:$bldver
fi

if [ "$(docker images -q clounix/platform/knet-build-env-$USER:$bldver 2> /dev/null)" == "" ]; then
  echo "Build Docker image as clounix/platform/knet-build-env-$USER:$bldver"
  docker image build \
               --network=host \
               --build-arg bldver=$bldver \
               --build-arg user=$USER \
               --build-arg uid=$(id -u) \
               --build-arg guid=$(id -g) \
               --build-arg homedir=/var/$USER \
               --build-arg hostname=$HOSTNAME \
               --build-arg workdir=$PWD \
               -t clounix/platform/knet-build-env-$USER:$bldver \
               -f ./Dockerfile.user \
               .
fi

knetdesk=knet-build-$USER
# execute commands 
if [ $# -ne 1 ]; then
  shift
  echo "$@ ..."
  docker run \
	  -v `pwd`:`pwd` \
	  -v $HOME:/var/$USER \
	  -v /etc/localtime:/etc/localtime:ro \
	  -v /etc/timezone:/etc/timezone:ro \
	  -w `pwd` \
	  --name $knetdesk \
	  -it --rm clounix/platform/knet-build-env-$USER:$bldver sh -c "$@"
else
  echo "Start bash ..."
  docker run \
	  -v `pwd`:`pwd` \
	  -v $HOME:/var/$USER \
	  -v /etc/localtime:/etc/localtime:ro \
	  -v /etc/timezone:/etc/timezone:ro \
	  -w `pwd` \
	  --name $knetdesk \
	  -it --rm clounix/platform/knet-build-env-$USER:$bldver bash
fi
