#!/usr/bin/env bash

bldver='1.0'

# make sure login docker registry
#docker login docker.clounix.com with your login password
#docker login registry.clounix.com with user/Clounix123

# check docker image for building
if [ "$(docker images -q docker.clounix.com/software/platform/tools/nb-knet/build-env:$bldver 2> /dev/null)" == "" ]; then
  echo "Pull Docker image"
  docker pull docker.clounix.com/software/platform/tools/nb-knet/build-env:$bldver
fi

if [ "$(docker images -q clounix/platform/knet-build-env-$USER:$bldver 2> /dev/null)" == "" ]; then
  echo "Build Docker image as clounix/platform/knet-build-env-$USER:$bldver"
  docker image build \
               --network=host \
               --build-arg bldver=$bldver \
               --build-arg user=$USER \
               --build-arg uid=$(id -u) \
               --build-arg guid=$(id -g) \
               --build-arg homedir=/var/$USER \
               --build-arg hostname=$HOSTNAME \
               --build-arg workdir=$PWD \
               -t clounix/platform/knet-build-env-$USER:$bldver \
               -f ./Dockerfile.user \
               .
fi

knetdesk=knet-build-$USER
# execute commands 
if [ $# -ne 0 ]; then
  echo "$@ ..."
  docker run \
	  -v `pwd`:`pwd` \
	  -v $HOME:/var/$USER \
	  -v /etc/localtime:/etc/localtime:ro \
	  -v /etc/timezone:/etc/timezone:ro \
	  -w `pwd` \
	  --name $knetdesk \
	  -it --rm clounix/platform/knet-build-env-$USER:$bldver sh -c "$@"
else
  echo "Start bash ..."
  docker run \
	  -v `pwd`:`pwd` \
	  -v $HOME:/var/$USER \
	  -v /etc/localtime:/etc/localtime:ro \
	  -v /etc/timezone:/etc/timezone:ro \
	  -w `pwd` \
	  --name $knetdesk \
	  -it --rm clounix/platform/knet-build-env-$USER:$bldver bash
fi
