/*******************************************************************************
*  Copyright Statement:
*  --------------------
*  This software and the information contained therein are protected by
*  copyright and other intellectual property laws and terms herein is
*  confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of Hangzhou Clounix Technology Limited. (C) 2020-2023
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("CLOUNIX SOFTWARE")
*  RECEIVED FROM CLOUNIX AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. CLOUNIX EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES CLOUNIX PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE CLOUNIX SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. CLOUNIX SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY CLOUNIX SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND CLOUNIX'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE CLOUNIX SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT CLOUNIX'S OPTION, TO REVISE OR REPLACE THE CLOUNIX SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  CLOUNIX FOR SUCH CLOUNIX SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE PEOPLE'S REPUBLIC OF CHINA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY LAWSUIT IN HANGZHOU,CHINA UNDER.
*
*******************************************************************************/

/* FILE NAME:  hal_lightning_pkt_rx_reason.h
 * PURPOSE:
 *      It provides hal pkt module API.
 * NOTES:
 *
 */

#ifndef HAL_LIGHTNING_PKT_RX_REASON_H
#define HAL_LIGHTNING_PKT_RX_REASON_H

/* INCLUDE FILE DECLARTIONS
 */
#include <clx_types.h>
#include <clx_error.h>
#include <hal/common/hal_tbl.h>

#define HAL_PKT_PP_REASON_STR_LEN       (64)

typedef UI32_T HAL_LIGHTNING_PKT_IPP_EXCPT_T;
typedef UI32_T HAL_LIGHTNING_PKT_EPP_EXCPT_T;

typedef enum
{
    HAL_LIGHTNING_PKT_IPP_L3_EXCPT_FCOE_ZONING = 0,
    HAL_LIGHTNING_PKT_IPP_L3_EXCPT_RPF,
    HAL_LIGHTNING_PKT_IPP_L3_EXCPT_ICMP_REDIR,
    HAL_LIGHTNING_PKT_IPP_L3_EXCPT_SW_FWD,
    HAL_LIGHTNING_PKT_IPP_L3_EXCPT_MTU,
    HAL_LIGHTNING_PKT_IPP_L3_EXCPT_TTL,
    HAL_LIGHTNING_PKT_IPP_L3_EXCPT_LAST
} HAL_LIGHTNING_PKT_IPP_L3_EXCPT_T;

typedef enum
{
    HAL_LIGHTNING_PKT_IPP_RSN_RSVD_0 = 0,
    HAL_LIGHTNING_PKT_IPP_RSN_IDS_MPLS_MP_LSP_INNER_IP_LCL,
    HAL_LIGHTNING_PKT_IPP_RSN_IDS_IP_MC_TNL_LCL_INTF_MISS,
    HAL_LIGHTNING_PKT_IPP_RSN_IDS_IP_MC_TNL_GRE_ISIS,
    HAL_LIGHTNING_PKT_IPP_RSN_IDS_IP_MC_TNL_GRE_KA,
    HAL_LIGHTNING_PKT_IPP_RSN_IDS_IP_MC_TNL_INNER_IP_LCL,
    HAL_LIGHTNING_PKT_IPP_RSN_IDS_TRILL_MC_LCL_INTF_MISS,
    HAL_LIGHTNING_PKT_IPP_RSN_IDS_INNER_SRV_1ST_MISS,
    HAL_LIGHTNING_PKT_IPP_RSN_IDS_INNER_SRV_2ND_MISS,
    HAL_LIGHTNING_PKT_IPP_RSN_IEV_IP_MC_TTL0,
    HAL_LIGHTNING_PKT_IPP_RSN_IEV_IP_MC_TTL1,
    HAL_LIGHTNING_PKT_IPP_RSN_RSVD_1,
    HAL_LIGHTNING_PKT_IPP_RSN_RSVD_2,
    HAL_LIGHTNING_PKT_IPP_RSN_IDS_ECN,
    HAL_LIGHTNING_PKT_IPP_RSN_IEV_ICMP_REDIR,
    HAL_LIGHTNING_PKT_IPP_RSN_IEV_ICMP_REDIR_WITH_RSN_IDS_ECN,
    HAL_LIGHTNING_PKT_IPP_RSN_LAST
} HAL_LIGHTNING_PKT_IPP_RSN_T;

typedef enum
{
    /* IEV.cp_to_cpu_bmap |=
     * (1UL << sw_plane.iev_cp_to_cpu_bit_pos_{i})   |
     * (1UL << sw_plane.iev_sflw_cp_to_cpu_bidx_{i}) |
     * (1UL << (IEV_RSLT_CTL2CPU_PROF.code - 1))     |
     * (1UL << (ICIA_RSLT_TCAM_UCP_POLICY.cp_to_cpu_idx - 1));
     */
    HAL_LIGHTNING_PKT_IPP_COPY2CPU_ICIA_0 = 0,
    HAL_LIGHTNING_PKT_IPP_COPY2CPU_ICIA_1,
    HAL_LIGHTNING_PKT_IPP_COPY2CPU_ICIA_2,
    HAL_LIGHTNING_PKT_IPP_COPY2CPU_ICIA_3,
    HAL_LIGHTNING_PKT_IPP_COPY2CPU_ICIA_4,
    HAL_LIGHTNING_PKT_IPP_COPY2CPU_ICIA_5,
    HAL_LIGHTNING_PKT_IPP_COPY2CPU_COPY_TO_CPU_L2UC,
    HAL_LIGHTNING_PKT_IPP_COPY2CPU_COPY_TO_CPU_L3UC,
    HAL_LIGHTNING_PKT_IPP_COPY2CPU_PORT_SFLOW,
    HAL_LIGHTNING_PKT_IPP_COPY2CPU_ICIA_SFLOW,
    HAL_LIGHTNING_PKT_IPP_COPY2CPU_FLOW_SFLOW,
    HAL_LIGHTNING_PKT_IPP_COPY2CPU_L3MC_SPT_READY_UNSET,
    HAL_LIGHTNING_PKT_IPP_COPY2CPU_COPY_TO_CPU_L2MC,
    HAL_LIGHTNING_PKT_IPP_COPY2CPU_COPY_TO_CPU_L3MC,
    HAL_LIGHTNING_PKT_IPP_COPY2CPU_USR_DEFINE_0,
    HAL_LIGHTNING_PKT_IPP_COPY2CPU_USR_DEFINE_1,
    HAL_LIGHTNING_PKT_IPP_COPY2CPU_LAST
} HAL_LIGHTNING_PKT_IPP_COPY2CPU_T;

typedef enum
{
    /* The value of:
     * 1. emi_sflw_cp_to_cpu_idx_bidx_*
     * 2. ECIA.cp_to_cpu_idx (last is invalid)
     */
    HAL_LIGHTNING_PKT_EPP_COPY2CPU_ECIA_0 = 0,
    HAL_LIGHTNING_PKT_EPP_COPY2CPU_ECIA_1,
    HAL_LIGHTNING_PKT_EPP_COPY2CPU_ECIA_2,
    HAL_LIGHTNING_PKT_EPP_COPY2CPU_ECIA_3,
    HAL_LIGHTNING_PKT_EPP_COPY2CPU_PORT_SFLOW,
    HAL_LIGHTNING_PKT_EPP_COPY2CPU_ECIA_SFLOW,
    HAL_LIGHTNING_PKT_EPP_COPY2CPU_SFLOW_HIGH_LATENCY,
    HAL_LIGHTNING_PKT_EPP_COPY2CPU_DTEL_IFA_SAMPLE, /* Packets with this reason aren't
                                       really copied to CPU in the use cases. */
    HAL_LIGHTNING_PKT_EPP_COPY2CPU_LAST
} HAL_LIGHTNING_PKT_EPP_COPY2CPU_T;

typedef enum
{
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_RSVD_0,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_VNTAG_UPS_DPL,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_VNTAG_DWS_D,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_VNTAG_INVLD,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_ETAG_INVLD,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_ECID_INVLD,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_VM_RPF_CK,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_L2_LCL_INTF_TYP,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_TAG_ERR,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_NVO3_L3_MTU,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_MPLS_EL_LE_15,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_MPLS_2ND_ELI,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_MPLS_ELI_BOS,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_MPLS_DECAP_TOP_GAL,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_MPLS_DECAP_TOP_XL,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_MPLS_DECAP_TOP_RSVD,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_MPLS_LBL_GT4,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_MPLS_SRV_RSLT_TYP,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_MPLS_DECAP_NULL_UHP_BOS_L2_HDR_PRESENT,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_MPLS_UHP_P2P_MISS,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_MPLS_LSP_MISS,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_MPLS_DECAP_UHP_IP_VER,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_MPLS_DECAP_MPLS_NULL_IPV4,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_MPLS_DECAP_MPLS_NULL_IPV6,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_MPLS_DECAP_HIT_GAL,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_MPLS_DECAP_HIT_XL,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_MPLS_DECAP_HIT_RSVD,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_MPLS_DECAP_HIT_BOS0,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_MPLS_UHP_TTL_0,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_MPLS_UHP_TTL_1,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_MPLS_TRANSIT_TTL_0,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_MPLS_TRANSIT_TTL_1,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_MPLS_INNER_IP_VER,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_MPLS_DECAP_TTL_0,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_MPLS_DECAP_TTL_1,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_MPLS_PW_CW,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_MPLS_PW_ACH,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_MPLS_PW_UNK,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_DPP_LOOPBACK,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_MPLS_P2P_LSP_INNER_IPV4_LCL,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_MPLS_P2P_LSP_INNER_IPV6_LCL,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_IP_TNL_TYP_NOT_ALW,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_IP_TNL_IPV4_FRAG,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_IP_TNL_IPV4_IHL,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_IP_TNL_IPV4_TTL_0,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_IP_TNL_IPV4_TTL_1,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_IP_TNL_IPV4_AH,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_IP_TNL_IPV6_FRAG,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_IP_TNL_IPV6_EXT,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_IP_TNL_IPV6_TTL_0,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_IP_TNL_IPV6_TTL_1,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_IP_TNL_IPV6_AH,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_L2_LCL_INTF_MISS,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_IP_TNL_INNER_IP_VER,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_GRE_ERSPAN_TYP_2_VER,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_GRE_ERSPAN_TYP_3_VER,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_GRE_ERSPAN_TYP_3_FT,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_AUTO_TNL_DA,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_AUTO_TNL_SA,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_ETH_IP_HDR,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_DECAP_FLEX_UDP_CKSUM_IPV4,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_DECAP_FLEX_UDP_CKSUM_IPV6,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_VXLAN_GPE_UDP_CKSUM_IPV4,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_VXLAN_GPE_UDP_CKSUM_IPV6,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_VXLAN_GPE_IFLG,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_VXLAN_GPE_CTL_FLG_0,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_VXLAN_GPE_CTL_FLG_1,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_VXLAN_GPE_CTL_FLG_2,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_VXLAN_GPE_CTL_FLG_3,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_VXLAN_BAS_UDP_CKSUM_IPV4,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_VXLAN_BAS_UDP_CKSUM_IPV6,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_VXLAN_BAS_IFLG,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_VXLAN_BAS_CTL_FLG,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_VXLAN_BAS_RSVD,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_GRE_VER,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_GRE_HDR_RSVD_FLD,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_GRE_CTL_FLG_0,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_GRE_CTL_FLG_1,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_GRE_CTL_FLG_2,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_GRE_CTL_FLG_3,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_IP_UC_TNL_INNER_IPV4_LCL,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_IP_UC_TNL_INNER_IPV6_LCL,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_GRE_ISIS,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_GRE_KA,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_ECN,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_TRILL_MC_MAC,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_TRILL_VER,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_TRILL_OP_LEN_MAX,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_TRILL_TRANSIT_TTL_1,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_TRILL_TRANSIT_TTL_0,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_TRILL_DECAP_TTL_1,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_TRILL_DECAP_TTL_0,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_TRILL_OPT,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_NSH_LEN_LT_2,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_TRANSIT_NSH_SRV_IDX_0,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_TRANSIT_NSH_OAM,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_TRANSIT_NSH_CRI,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_TRANSIT_NSH_RSVD,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_DECAP_NSH_OAM,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_DECAP_NSH_CRI,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_DECAP_NSH_RSVD,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_DECAP_NSH_CL_INVLD,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_DECAP_NSH_LEN_GT_6,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_IPV4_VER,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_UL_L2_VLAN_1ST_MISS,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_UL_L2_VLAN_UNEXP,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_NTO1_INNER_VLAN_MISS,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_INNER_SRV_1ST_MISS,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_INNER_SRV_2ND_MISS,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_RSLT_SRV_U_L2_INTF_IDX_FF,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_RSLT_SRV_U_L2_INTF_IDX_FE,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_L3_MTU,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_IPV4_MC_L2_DA_MALFORMED,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_IPV6_MC_L2_DA_MALFORMED,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_FCOE_VER_BAD,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_L3_TNL_INNER_IP_RTE_NOT_EN,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_IPV4_CKSUM,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_IPV4_IHL_LT_5,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_IPV4_TLEN_LT_IHL,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_IPV6_VER,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_IPV6_HDR_TRUNCATED,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_PPPOE_SRV_UNK,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_PPPOE_HDR,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_IP_TNL_IPV4_VER,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_IP_TNL_IPV6_VER,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_DECAP_NSH_TTL,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_TRANSIT_NSH_TTL,
    HAL_LIGHTNING_PKT_IPP_REASON_IDS_SDK_DOS_CHK_0,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_TRILL_UC_ADJ,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L3_MTU,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_NVO3_RSLT_ECMP_PATH_U_EP_L3_TYP,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_NVO3_ENCAP_IDX_INVLD,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_NVO3_ENCAP_INVLD,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L3_ECMP_PATH_TYP,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L2_UEID_INVLD,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L2_ECMP_PATH_TYP,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L3_UEID_INVLD,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L2_SA_MISS,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L2_SA_MOVE,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_RSVD0,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_STACKING_LOOP,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L2_SRC_SUPP,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L25_NSH_MISS,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_RSLT_BNK_TYP_L25_NSH,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_RSLT_BNK_TYP_L2_INDIR,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_RSLT_BNK_TYP_L3_INDIR,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_RSLT_BNK_TYP_FLW,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_FLW_ICIA_3X_INVLD_IDX,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_STM_CTL,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L2_TOPO_BLK,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_ARP_SRC_GUARD,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L3_IPV4_SRC_GUARD,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L3_IPV6_SRC_GUARD,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L3_FCOE_SRC_GUARD,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_TRILL_MC_ADJ,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_TRILL_MC_RPF,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_RSLT_BNK_TYP_L4,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_RSLT_BNK_TYP_L2,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_RSLT_BNK_TYP_L3,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L2_DA_TYP,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L2_SA_TYP,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L25_MISS,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L25_TYP,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L3_SW_FWD_IPV4,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L3_SW_FWD_IPV6,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L3_FCOE_EXT_UNK,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L3_FCOE_DID_MISS,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L3_FCOE_TYP,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L3_FCOE_ZONING,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L3_FCOE_TTL,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L3_DA_TYP,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L3_IPV4_TTL_0,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L3_IPV4_TTL_1,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L3_IPV6_TTL_0,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L3_IPV6_TTL_1,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L3_IPV4_ICMP_REDIR,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L3_IPV6_ICMP_REDIR,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L3_IPV4_MRPF,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L3_IPV6_MRPF,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L3_IPV4_MC_MISS,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L3_IPV6_MC_MISS,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L3_IPV4_MC_BRIDGED_CP_TTL_0,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L3_IPV6_MC_BRIDGED_CP_TTL_0,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L3_SA_TYP,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L3_IPV4_URPF,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L3_IPV6_URPF,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_PBR_FLW_TYP,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_NSH_POP_LEN_GT_6,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_NSH_POP_CL_INVLD,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_NSH_POP_INVLD_IP_VER,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_PBR_DROP,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_ECC,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_PORT_ISO,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_LRN_CLS,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_PORT_MTR,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_L3_MTU_IGR,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_WECMP,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_RSVD_0,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_RSVD_1,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_RSVD_2,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_RSVD_3,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_USER_DEFINED_0,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_USER_DEFINED_1,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_USER_DEFINED_2,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_USER_DEFINED_3,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_USER_DEFINED_4,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_USER_DEFINED_5,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_USER_DEFINED_6,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_USER_DEFINED_7,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_USER_DEFINED_8,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_USER_DEFINED_9,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_USER_DEFINED_10,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_USER_DEFINED_11,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_USER_DEFINED_12,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_USER_DEFINED_13,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_REDIRECT_TO_CPU_L2UC,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_REDIRECT_TO_CPU_L3UC,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_MIRROR_ERSPAN_MISS,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_1588_RX,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_VM_BFD,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_VM_FDB_MISS,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_L3_BFD,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_L3UC_DA_MISS,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_L3MC_PIM_REGISTER,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_ICIA_REDIRECT_0,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_ICIA_REDIRECT_1,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_ICIA_REDIRECT_2,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_ICIA_REDIRECT_3,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_ICIA_REDIRECT_4,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_ICIA_REDIRECT_5,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_ICIA_REDIRECT_6,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_ICIA_REDIRECT_7,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_FLEX_DECAP_0_REASON_0,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_FLEX_DECAP_0_REASON_1,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_FLEX_DECAP_0_REASON_2,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_FLEX_DECAP_0_REASON_3,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_FLEX_DECAP_0_REASON_4,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_FLEX_DECAP_0_REASON_5,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_FLEX_DECAP_1_REASON_0,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_FLEX_DECAP_1_REASON_1,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_FLEX_DECAP_1_REASON_2,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_FLEX_DECAP_1_REASON_3,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_FLEX_DECAP_1_REASON_4,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_FLEX_DECAP_1_REASON_5,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_FLEX_DECAP_2_REASON_0,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_FLEX_DECAP_2_REASON_1,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_FLEX_DECAP_2_REASON_2,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_FLEX_DECAP_2_REASON_3,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_FLEX_DECAP_2_REASON_4,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_FLEX_DECAP_2_REASON_5,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_FLEX_DECAP_3_REASON_0,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_FLEX_DECAP_3_REASON_1,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_FLEX_DECAP_3_REASON_2,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_FLEX_DECAP_3_REASON_3,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_FLEX_DECAP_3_REASON_4,
    HAL_LIGHTNING_PKT_IPP_REASON_IEV_SDK_FLEX_DECAP_3_REASON_5,
    HAL_LIGHTNING_PKT_IPP_REASON_LAST = 512,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_RSVD_0 = 512,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_HDR_INCR_LCL,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_DECAP_HDR_MISS,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_DECAP_ACT_INVLD,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_DECAP_FLEX_INVLD,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_MPLS_ELI_BOS,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_MPLS_ELI_EL_NON_IP,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_MPLS_POP_BEYOND_BOS,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_MPLS_2ND_ELI,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_PHP_POP_EXPOSE_NON_IP,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_MPLS_ENTROPY_BOS,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_MPLS_DECAP_EXPOSE_NON_IP,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_TRILL_TRANSIT_ADJ_IDX_INVLD,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_ADJ_RSLT_BNK_INVLD,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_L3_ADJ_IDX_INVLD,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_L2_HDR_MISS,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_L3_MTU,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_L3_IPV4_TTL_1,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_L3_IPV6_TTL_1,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_SRC_SUPP,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_FCM_RSLT_BNK_INVLD,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_L25_UC_TURN_MC,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_L2_TOPO_BLK,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_ECIA_DROP,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_NSH_O_NSH,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_NSH_UNK_ETYP,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_NSH_RSLT_BNK_INVLD,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_NSH_O_TNL_INVLD,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_NSH_NXT_PTR,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_IP_TNL_TYP,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_MPLS_NXT_PTR,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_MPLS_O_UNK_IP_TNL,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_TRILL_ENCAP_FGL,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_TRILL_ENCAP_VL,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_NVO3_L3_MTU,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_PORT_ISO,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_FCM_TLV_TYP_ORDERS,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_FCM_TLV_BIDX_ASCEND,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_FCM_TLV_OOR,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_FCM_TLV_TOT,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_FCM_REWR_IDX_OVERLAP,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_FCM_TLV_TOT_4X,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_FCM_TLV_CHG_BLST,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_FCM_TLV_INS_BLST,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_SRV_IDX_INVLD,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_FCM_TLV_INS_DEL_OVERLAP,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_FCM_TLV_INS_INVLD,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_FCM_TLV_DEL_INVLD,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_RSVD_1,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_RSVD_2,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_RSVD_3,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_PPPOE_SRV_UNK,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_PPPOE_ENCAP,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_IOAM_NODELEN_MIS_ALGN_IPV6,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_IOAM_NODELEN_MIS_ALGN_GRE,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_IOAM_NODELEN_MIS_ALGN_GPE,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_IOAM_DEL,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_IFA_DEL,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_RSVD_4,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_RSVD_5,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_RSVD_6,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_RSVD_7,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_RSVD_8,
    HAL_LIGHTNING_PKT_EPP_REASON_EME_RSVD_9,
    HAL_LIGHTNING_PKT_EPP_REASON_LAST = 768
} HAL_LIGHTNING_PKT_PP_REASON_T;

typedef struct
{
    CLX_PKT_RX_REASON_T                     user_reason;
    HAL_LIGHTNING_PKT_IPP_EXCPT_T                 ipp_excpt;
} HAL_LIGHTNING_PKT_REASON_MAP_IPP_EXCPT_T;

typedef struct
{
    CLX_PKT_RX_REASON_T                     user_reason;
    HAL_LIGHTNING_PKT_IPP_L3_EXCPT_T              ipp_l3_excpt;
} HAL_LIGHTNING_PKT_REASON_MAP_IPP_L3_EXCPT_T;

typedef struct
{
    CLX_PKT_RX_REASON_T                     user_reason;
    HAL_LIGHTNING_PKT_EPP_EXCPT_T                 epp_excpt;
} HAL_LIGHTNING_PKT_REASON_MAP_EPP_EXCPT_T;

typedef struct
{
    CLX_PKT_RX_REASON_T                     user_reason;
    HAL_LIGHTNING_PKT_IPP_RSN_T                   ipp_rsn;
} HAL_LIGHTNING_PKT_REASON_MAP_IPP_RSN_T;

typedef struct
{
    CLX_PKT_RX_REASON_T                     user_reason;
    HAL_LIGHTNING_PKT_IPP_COPY2CPU_T              ipp_copy2cpu;
} HAL_LIGHTNING_PKT_REASON_MAP_IPP_COPY2CPU_T;

typedef struct
{
    CLX_PKT_RX_REASON_T                     user_reason;
    HAL_LIGHTNING_PKT_EPP_COPY2CPU_T              epp_copy2cpu;
} HAL_LIGHTNING_PKT_REASON_MAP_EPP_COPY2CPU_T;

typedef struct
{
    HAL_LIGHTNING_PKT_PP_REASON_T pp_reason;
    C8_T                          str_pp_reason[HAL_PKT_PP_REASON_STR_LEN];
} HAL_LIGHTNING_PKT_PP_REASON_STR_T;

/* Note: the _hal_lightning_pkt_user_reason_to_ipp_excpt table should be organized in a way that
 * we can use HW value as index to lookup for user reason. Any future modification should
 * consider this!!!
 */
static HAL_LIGHTNING_PKT_REASON_MAP_IPP_EXCPT_T           _hal_lightning_pkt_user_reason_to_ipp_excpt[] =
{
    /* P: proto-excption
     * S: sw-definition
     */
    /* -------------------------------------------- 0 ----------------------------------------------------------- */
    {CLX_PKT_RX_REASON_OTHERS,                      IDS_CFG_EXCPT_EN_W3_RSVD_0_FIELD_ID                     },
    {CLX_PKT_RX_REASON_VCLAG_INVALID,               IDS_CFG_EXCPT_EN_W3_VNTAG_UPS_DPL_FIELD_ID              },
    {CLX_PKT_RX_REASON_VCLAG_INVALID,               IDS_CFG_EXCPT_EN_W3_VNTAG_DWS_D_FIELD_ID                },
    {CLX_PKT_RX_REASON_VCLAG_INVALID,               IDS_CFG_EXCPT_EN_W3_VNTAG_INVLD_FIELD_ID                },
    {CLX_PKT_RX_REASON_VCLAG_INVALID,               IDS_CFG_EXCPT_EN_W3_ETAG_INVLD_FIELD_ID                 },
    {CLX_PKT_RX_REASON_VCLAG_INVALID,               IDS_CFG_EXCPT_EN_W3_ECID_INVLD_FIELD_ID                 },
    {CLX_PKT_RX_REASON_VM_RPF_FAIL,                 IDS_CFG_EXCPT_EN_W3_VM_RPF_CK_FIELD_ID                  },
    {CLX_PKT_RX_REASON_L2_LKP_MISS,                 IDS_CFG_EXCPT_EN_W3_L2_LCL_INTF_TYP_FIELD_ID            },
    {CLX_PKT_RX_REASON_VLAN_MISS_VLAN_CHK,          IDS_CFG_EXCPT_EN_W3_TAG_ERR_FIELD_ID                    },
    {CLX_PKT_RX_REASON_IGR_TUNNEL_MTU_FAIL,         IDS_CFG_EXCPT_EN_W3_NVO3_L3_MTU_FIELD_ID                },
    {CLX_PKT_RX_REASON_MPLS_INVALID_PKT,            IDS_CFG_EXCPT_EN_W3_MPLS_EL_LE_15_FIELD_ID              },
    {CLX_PKT_RX_REASON_MPLS_INVALID_PKT,            IDS_CFG_EXCPT_EN_W3_MPLS_2ND_ELI_FIELD_ID               },
    {CLX_PKT_RX_REASON_MPLS_INVALID_PKT,            IDS_CFG_EXCPT_EN_W3_MPLS_ELI_BOS_FIELD_ID               },
    {CLX_PKT_RX_REASON_MPLS_CTRL_PKT,               IDS_CFG_EXCPT_EN_W3_MPLS_DECAP_TOP_GAL_FIELD_ID         }, /* P */
    {CLX_PKT_RX_REASON_MPLS_CTRL_PKT,               IDS_CFG_EXCPT_EN_W3_MPLS_DECAP_TOP_XL_FIELD_ID          },
    {CLX_PKT_RX_REASON_MPLS_CTRL_PKT,               IDS_CFG_EXCPT_EN_W3_MPLS_DECAP_TOP_RSVD_FIELD_ID        },
    {CLX_PKT_RX_REASON_MPLS_INVALID_PKT,            IDS_CFG_EXCPT_EN_W3_MPLS_LBL_GT4_FIELD_ID               },
    {CLX_PKT_RX_REASON_MPLS_LKP_MISS,               IDS_CFG_EXCPT_EN_W3_MPLS_SRV_RSLT_TYP_FIELD_ID          },
    {CLX_PKT_RX_REASON_MPLS_INVALID_PKT,            IDS_CFG_EXCPT_EN_W3_MPLS_DECAP_NULL_UHP_BOS_L2_HDR_PRESENT_FIELD_ID},
    {CLX_PKT_RX_REASON_MPLS_UHP_P2P_MISS,           IDS_CFG_EXCPT_EN_W3_MPLS_UHP_P2P_MISS_FIELD_ID          },
    {CLX_PKT_RX_REASON_MPLS_LKP_MISS,               IDS_CFG_EXCPT_EN_W3_MPLS_LSP_MISS_FIELD_ID              },
    {CLX_PKT_RX_REASON_MPLS_INVALID_PKT,            IDS_CFG_EXCPT_EN_W3_MPLS_DECAP_UHP_IP_VER_FIELD_ID      },
    {CLX_PKT_RX_REASON_MPLS_INVALID_PKT,            IDS_CFG_EXCPT_EN_W3_MPLS_DECAP_MPLS_NULL_IPV4_FIELD_ID  },
    {CLX_PKT_RX_REASON_MPLS_INVALID_PKT,            IDS_CFG_EXCPT_EN_W3_MPLS_DECAP_MPLS_NULL_IPV6_FIELD_ID  },
    {CLX_PKT_RX_REASON_MPLS_CTRL_PKT,               IDS_CFG_EXCPT_EN_W3_MPLS_DECAP_HIT_GAL_FIELD_ID         }, /* P */
    {CLX_PKT_RX_REASON_MPLS_CTRL_PKT,               IDS_CFG_EXCPT_EN_W3_MPLS_DECAP_HIT_XL_FIELD_ID          },
    {CLX_PKT_RX_REASON_MPLS_CTRL_PKT,               IDS_CFG_EXCPT_EN_W3_MPLS_DECAP_HIT_RSVD_FIELD_ID        },
    {CLX_PKT_RX_REASON_MPLS_INVALID_PKT,            IDS_CFG_EXCPT_EN_W3_MPLS_DECAP_HIT_BOS0_FIELD_ID        },
    {CLX_PKT_RX_REASON_MPLS_UHP_TTL_0,              IDS_CFG_EXCPT_EN_W3_MPLS_UHP_TTL_0_FIELD_ID             },
    {CLX_PKT_RX_REASON_MPLS_UHP_TTL_1,              IDS_CFG_EXCPT_EN_W3_MPLS_UHP_TTL_1_FIELD_ID             },
    {CLX_PKT_RX_REASON_MPLS_TRANSIT_TTL_0,          IDS_CFG_EXCPT_EN_W3_MPLS_TRANSIT_TTL_0_FIELD_ID         },
    {CLX_PKT_RX_REASON_MPLS_TRANSIT_TTL_1,          IDS_CFG_EXCPT_EN_W3_MPLS_TRANSIT_TTL_1_FIELD_ID         },

    /* -------------------------------------------- 32 ---------------------------------------------------------- */
    {CLX_PKT_RX_REASON_MPLS_INVALID_PKT,            IDS_CFG_EXCPT_EN_W2_MPLS_INNER_IP_VER_FIELD_ID          },
    {CLX_PKT_RX_REASON_MPLS_TERM_TTL_0,             IDS_CFG_EXCPT_EN_W2_MPLS_DECAP_TTL_0_FIELD_ID           },
    {CLX_PKT_RX_REASON_MPLS_TERM_TTL_1,             IDS_CFG_EXCPT_EN_W2_MPLS_DECAP_TTL_1_FIELD_ID           },
    {CLX_PKT_RX_REASON_MPLS_CTRL_PKT,               IDS_CFG_EXCPT_EN_W2_MPLS_PW_CW_FIELD_ID                 },
    {CLX_PKT_RX_REASON_MPLS_CTRL_PKT,               IDS_CFG_EXCPT_EN_W2_MPLS_PW_ACH_FIELD_ID                }, /* P */
    {CLX_PKT_RX_REASON_MPLS_INVALID_PKT,            IDS_CFG_EXCPT_EN_W2_MPLS_PW_UNK_FIELD_ID                },
    {CLX_PKT_RX_REASON_DPP_LOOPBACK,                IDS_CFG_EXCPT_EN_W2_DPP_LOOPBACK_FIELD_ID               },
    {CLX_PKT_RX_REASON_MPLS_CTRL_PKT,               IDS_CFG_EXCPT_EN_W2_MPLS_P2P_LSP_INNER_IPV4_LCL_FIELD_ID}, /* P */
    {CLX_PKT_RX_REASON_MPLS_CTRL_PKT,               IDS_CFG_EXCPT_EN_W2_MPLS_P2P_LSP_INNER_IPV6_LCL_FIELD_ID}, /* P */
    {CLX_PKT_RX_REASON_TUNNEL_TERM_LKP_MISS,        IDS_CFG_EXCPT_EN_W2_IP_TNL_TYP_NOT_ALW_FIELD_ID         },
    {CLX_PKT_RX_REASON_IP_TUNNEL_OUTER_IPV4_FRAG,   IDS_CFG_EXCPT_EN_W2_IP_TNL_IPV4_FRAG_FIELD_ID           },
    {CLX_PKT_RX_REASON_IP_TUNNEL_OUTER_IPV4_OPT,    IDS_CFG_EXCPT_EN_W2_IP_TNL_IPV4_IHL_FIELD_ID            },
    {CLX_PKT_RX_REASON_IP_TUNNEL_OUTER_IPV4_TTL_0,  IDS_CFG_EXCPT_EN_W2_IP_TNL_IPV4_TTL_0_FIELD_ID          },
    {CLX_PKT_RX_REASON_IP_TUNNEL_OUTER_IPV4_TTL_1,  IDS_CFG_EXCPT_EN_W2_IP_TNL_IPV4_TTL_1_FIELD_ID          },
    {CLX_PKT_RX_REASON_IP_TUNNEL_OUTER_IPV4_AH,     IDS_CFG_EXCPT_EN_W2_IP_TNL_IPV4_AH_FIELD_ID             },
    {CLX_PKT_RX_REASON_IP_TUNNEL_OUTER_IPV6_FRAG,   IDS_CFG_EXCPT_EN_W2_IP_TNL_IPV6_FRAG_FIELD_ID           },
    {CLX_PKT_RX_REASON_IP_TUNNEL_OUTER_IPV6_OPT,    IDS_CFG_EXCPT_EN_W2_IP_TNL_IPV6_EXT_FIELD_ID            },
    {CLX_PKT_RX_REASON_IP_TUNNEL_OUTER_IPV6_TTL_0,  IDS_CFG_EXCPT_EN_W2_IP_TNL_IPV6_TTL_0_FIELD_ID          },
    {CLX_PKT_RX_REASON_IP_TUNNEL_OUTER_IPV6_TTL_1,  IDS_CFG_EXCPT_EN_W2_IP_TNL_IPV6_TTL_1_FIELD_ID          },
    {CLX_PKT_RX_REASON_IP_TUNNEL_OUTER_IPV6_AH,     IDS_CFG_EXCPT_EN_W2_IP_TNL_IPV6_AH_FIELD_ID             },
    {CLX_PKT_RX_REASON_TUNNEL_TERM_LKP_MISS,        IDS_CFG_EXCPT_EN_W2_L2_LCL_INTF_MISS_FIELD_ID           },
    {CLX_PKT_RX_REASON_IP_TUNNEL_INNER_VER_ERR,     IDS_CFG_EXCPT_EN_W2_IP_TNL_INNER_IP_VER_FIELD_ID        },
    {CLX_PKT_RX_REASON_GRE_ERSPAN_TYP2_VER_ERR,     IDS_CFG_EXCPT_EN_W2_GRE_ERSPAN_TYP_2_VER_FIELD_ID       },
    {CLX_PKT_RX_REASON_GRE_ERSPAN_TYP3_VER_ERR,     IDS_CFG_EXCPT_EN_W2_GRE_ERSPAN_TYP_3_VER_FIELD_ID       },
    {CLX_PKT_RX_REASON_GRE_ERSPAN_TYP3_FT_ERR,      IDS_CFG_EXCPT_EN_W2_GRE_ERSPAN_TYP_3_FT_FIELD_ID        },
    {CLX_PKT_RX_REASON_AUTO_TUNNEL_DIP_MISS,        IDS_CFG_EXCPT_EN_W2_AUTO_TNL_DA_FIELD_ID                },
    {CLX_PKT_RX_REASON_AUTO_TUNNEL_SIP_MISS,        IDS_CFG_EXCPT_EN_W2_AUTO_TNL_SA_FIELD_ID                },
    /* IDS_CFG_EXCPT_EN_W2_ETH_IP_HDR is not supported in CL8570, reserve this bit for DOS_CHK_1 */
    {CLX_PKT_RX_REASON_DOS_CHK,                     IDS_CFG_EXCPT_EN_W2_ETH_IP_HDR_FIELD_ID                 },
    {CLX_PKT_RX_REASON_FLEX_TUNNEL_UDP_CHKSM_ERR,   IDS_CFG_EXCPT_EN_W2_DECAP_FLEX_UDP_CKSUM_IPV4_FIELD_ID  },
    {CLX_PKT_RX_REASON_FLEX_TUNNEL_UDP_CHKSM_ERR,   IDS_CFG_EXCPT_EN_W2_DECAP_FLEX_UDP_CKSUM_IPV6_FIELD_ID  },
    {CLX_PKT_RX_REASON_VXLAN_GPE_UDP_CHKSM_ERR,     IDS_CFG_EXCPT_EN_W2_VXLAN_GPE_UDP_CKSUM_IPV4_FIELD_ID   },
    {CLX_PKT_RX_REASON_VXLAN_GPE_UDP_CHKSM_ERR,     IDS_CFG_EXCPT_EN_W2_VXLAN_GPE_UDP_CKSUM_IPV6_FIELD_ID   },

    /* -------------------------------------------- 64 ---------------------------------------------------------- */
    {CLX_PKT_RX_REASON_VXLAN_GPE_VNI_FLAG_ERR,      IDS_CFG_EXCPT_EN_W1_VXLAN_GPE_IFLG_FIELD_ID             }, /* P */
    {CLX_PKT_RX_REASON_VXLAN_GPE_CTRL_FLAG_ERR,     IDS_CFG_EXCPT_EN_W1_VXLAN_GPE_CTL_FLG_0_FIELD_ID        },
    {CLX_PKT_RX_REASON_VXLAN_GPE_CTRL_FLAG_ERR,     IDS_CFG_EXCPT_EN_W1_VXLAN_GPE_CTL_FLG_1_FIELD_ID        },
    {CLX_PKT_RX_REASON_VXLAN_GPE_CTRL_FLAG_ERR,     IDS_CFG_EXCPT_EN_W1_VXLAN_GPE_CTL_FLG_2_FIELD_ID        },
    {CLX_PKT_RX_REASON_VXLAN_GPE_CTRL_FLAG_ERR,     IDS_CFG_EXCPT_EN_W1_VXLAN_GPE_CTL_FLG_3_FIELD_ID        },
    {CLX_PKT_RX_REASON_VXLAN_BAS_UDP_CHKSM_ERR,     IDS_CFG_EXCPT_EN_W1_VXLAN_BAS_UDP_CKSUM_IPV4_FIELD_ID   },
    {CLX_PKT_RX_REASON_VXLAN_BAS_UDP_CHKSM_ERR,     IDS_CFG_EXCPT_EN_W1_VXLAN_BAS_UDP_CKSUM_IPV6_FIELD_ID   },
    {CLX_PKT_RX_REASON_VXLAN_BAS_VNI_FLAG_ERR,      IDS_CFG_EXCPT_EN_W1_VXLAN_BAS_IFLG_FIELD_ID             }, /* P */
    {CLX_PKT_RX_REASON_VXLAN_BAS_CTRL_FLAG_ERR,     IDS_CFG_EXCPT_EN_W1_VXLAN_BAS_CTL_FLG_FIELD_ID          }, /* P */
    {CLX_PKT_RX_REASON_VXLAN_BAS_RSVD_NON_ZERO,     IDS_CFG_EXCPT_EN_W1_VXLAN_BAS_RSVD_FIELD_ID             },
    {CLX_PKT_RX_REASON_GRE_VER_ERR,                 IDS_CFG_EXCPT_EN_W1_GRE_VER_FIELD_ID                    }, /* P */
    {CLX_PKT_RX_REASON_GRE_RSVD_NON_ZERO,           IDS_CFG_EXCPT_EN_W1_GRE_HDR_RSVD_FLD_FIELD_ID           }, /* P */
    {CLX_PKT_RX_REASON_GRE_CTRL_FLAG_ERR,           IDS_CFG_EXCPT_EN_W1_GRE_CTL_FLG_0_FIELD_ID              }, /* P */
    {CLX_PKT_RX_REASON_GRE_CTRL_FLAG_ERR,           IDS_CFG_EXCPT_EN_W1_GRE_CTL_FLG_1_FIELD_ID              }, /* P */
    {CLX_PKT_RX_REASON_GRE_CTRL_FLAG_ERR,           IDS_CFG_EXCPT_EN_W1_GRE_CTL_FLG_2_FIELD_ID              }, /* P */
    {CLX_PKT_RX_REASON_GRE_CTRL_FLAG_ERR,           IDS_CFG_EXCPT_EN_W1_GRE_CTL_FLG_3_FIELD_ID              }, /* P */
    {CLX_PKT_RX_REASON_IP_TUNNEL_INNER_IPV4_UC_LCL, IDS_CFG_EXCPT_EN_W1_IP_UC_TNL_INNER_IPV4_LCL_FIELD_ID   }, /* P */
    {CLX_PKT_RX_REASON_IP_TUNNEL_INNER_IPV6_UC_LCL, IDS_CFG_EXCPT_EN_W1_IP_UC_TNL_INNER_IPV6_LCL_FIELD_ID   }, /* P */
    {CLX_PKT_RX_REASON_IP_TUNNEL_CTRL_PKT,          IDS_CFG_EXCPT_EN_W1_GRE_ISIS_FIELD_ID                   }, /* P */
    {CLX_PKT_RX_REASON_IP_TUNNEL_CTRL_PKT,          IDS_CFG_EXCPT_EN_W1_GRE_KA_FIELD_ID                     }, /* P */
    {CLX_PKT_RX_REASON_TUNNEL_ECN_CU,               IDS_CFG_EXCPT_EN_W1_ECN_FIELD_ID                        },
    {CLX_PKT_RX_REASON_TRILL_MC_FLAG_ERR,           IDS_CFG_EXCPT_EN_W1_TRILL_MC_MAC_FIELD_ID               },
    {CLX_PKT_RX_REASON_TRILL_VER_ERR,               IDS_CFG_EXCPT_EN_W1_TRILL_VER_FIELD_ID                  },
    {CLX_PKT_RX_REASON_TRILL_OPT,                   IDS_CFG_EXCPT_EN_W1_TRILL_OP_LEN_MAX_FIELD_ID           },
    {CLX_PKT_RX_REASON_TRILL_TRANSIT_TTL_1,         IDS_CFG_EXCPT_EN_W1_TRILL_TRANSIT_TTL_1_FIELD_ID        },
    {CLX_PKT_RX_REASON_TRILL_TRANSIT_TTL_0,         IDS_CFG_EXCPT_EN_W1_TRILL_TRANSIT_TTL_0_FIELD_ID        },
    {CLX_PKT_RX_REASON_TRILL_TERM_TTL_1,            IDS_CFG_EXCPT_EN_W1_TRILL_DECAP_TTL_1_FIELD_ID          },
    {CLX_PKT_RX_REASON_TRILL_TERM_TTL_0,            IDS_CFG_EXCPT_EN_W1_TRILL_DECAP_TTL_0_FIELD_ID          },
    {CLX_PKT_RX_REASON_TRILL_OPT,                   IDS_CFG_EXCPT_EN_W1_TRILL_OPT_FIELD_ID                  },
    {CLX_PKT_RX_REASON_NSH_INVALID_PKT,             IDS_CFG_EXCPT_EN_W1_NSH_LEN_LT_2_FIELD_ID               },
    {CLX_PKT_RX_REASON_NSH_INVALID_PKT,             IDS_CFG_EXCPT_EN_W1_TRANSIT_NSH_SRV_IDX_0_FIELD_ID      },
    {CLX_PKT_RX_REASON_NSH_CTRL_PKT,                IDS_CFG_EXCPT_EN_W1_TRANSIT_NSH_OAM_FIELD_ID            },

    /* -------------------------------------------- 96 ---------------------------------------------------------- */
    {CLX_PKT_RX_REASON_NSH_CTRL_PKT,                IDS_CFG_EXCPT_EN_W0_TRANSIT_NSH_CRI_FIELD_ID            },
    {CLX_PKT_RX_REASON_NSH_INVALID_PKT,             IDS_CFG_EXCPT_EN_W0_TRANSIT_NSH_RSVD_FIELD_ID           },
    {CLX_PKT_RX_REASON_NSH_CTRL_PKT,                IDS_CFG_EXCPT_EN_W0_DECAP_NSH_OAM_FIELD_ID              },
    {CLX_PKT_RX_REASON_NSH_CTRL_PKT,                IDS_CFG_EXCPT_EN_W0_DECAP_NSH_CRI_FIELD_ID              },
    {CLX_PKT_RX_REASON_NSH_INVALID_PKT,             IDS_CFG_EXCPT_EN_W0_DECAP_NSH_RSVD_FIELD_ID             },
    {CLX_PKT_RX_REASON_NSH_INVALID_PKT,             IDS_CFG_EXCPT_EN_W0_DECAP_NSH_CL_INVLD_FIELD_ID         },
    {CLX_PKT_RX_REASON_NSH_INVALID_PKT,             IDS_CFG_EXCPT_EN_W0_DECAP_NSH_LEN_GT_6_FIELD_ID         },
    {CLX_PKT_RX_REASON_IPV4_VER_ERR,                IDS_CFG_EXCPT_EN_W0_IPV4_VER_FIELD_ID                   },
    {CLX_PKT_RX_REASON_TUNNEL_INNER_VLAN_MISS,      IDS_CFG_EXCPT_EN_W0_UL_L2_VLAN_1ST_MISS_FIELD_ID        },
    {CLX_PKT_RX_REASON_TUNNEL_INNER_VLAN_UNEXP,     IDS_CFG_EXCPT_EN_W0_UL_L2_VLAN_UNEXP_FIELD_ID           },
    {CLX_PKT_RX_REASON_TUNNEL_INNER_VLAN_MISS,      IDS_CFG_EXCPT_EN_W0_NTO1_INNER_VLAN_MISS_FIELD_ID       },
    {CLX_PKT_RX_REASON_IPUC_TUNNEL_INNER_VLAN_MISS, IDS_CFG_EXCPT_EN_W0_INNER_SRV_1ST_MISS_FIELD_ID         },
    {CLX_PKT_RX_REASON_IPUC_TUNNEL_INNER_VLAN_MISS, IDS_CFG_EXCPT_EN_W0_INNER_SRV_2ND_MISS_FIELD_ID         },
    {CLX_PKT_RX_REASON_L2_LKP_MISS,                 IDS_CFG_EXCPT_EN_W0_RSLT_SRV_U_L2_INTF_IDX_FF_FIELD_ID  },
    {CLX_PKT_RX_REASON_L2_LKP_MISS,                 IDS_CFG_EXCPT_EN_W0_RSLT_SRV_U_L2_INTF_IDX_FE_FIELD_ID  },
    /* CLX_PKT_RX_REASON_IGR_L3_MTU_FAIL is not used in CL8570, reserve this bit for DOS_CHK_2 */
    {CLX_PKT_RX_REASON_DOS_CHK,                     IDS_CFG_EXCPT_EN_W0_L3_MTU_FIELD_ID                     },
    {CLX_PKT_RX_REASON_IPV4_MC_MALFORMED,           IDS_CFG_EXCPT_EN_W0_IPV4_MC_L2_DA_MALFORMED_FIELD_ID    },
    {CLX_PKT_RX_REASON_IPV6_MC_MALFORMED,           IDS_CFG_EXCPT_EN_W0_IPV6_MC_L2_DA_MALFORMED_FIELD_ID    },
    {CLX_PKT_RX_REASON_FCOE_VER_ERR,                IDS_CFG_EXCPT_EN_W0_FCOE_VER_BAD_FIELD_ID               },
    {CLX_PKT_RX_REASON_IP_TUNNEL_INNER_L3_ROUTE,    IDS_CFG_EXCPT_EN_W0_L3_TNL_INNER_IP_RTE_NOT_EN_FIELD_ID },
    {CLX_PKT_RX_REASON_IPV4_CHKSM_ERR,              IDS_CFG_EXCPT_EN_W0_IPV4_CKSUM_FIELD_ID                 },
    {CLX_PKT_RX_REASON_IPV4_OPT,                    IDS_CFG_EXCPT_EN_W0_IPV4_IHL_LT_5_FIELD_ID              },
    {CLX_PKT_RX_REASON_IPV4_LEN_ERR,                IDS_CFG_EXCPT_EN_W0_IPV4_TLEN_LT_IHL_FIELD_ID           },
    {CLX_PKT_RX_REASON_IPV6_VER_ERR,                IDS_CFG_EXCPT_EN_W0_IPV6_VER_FIELD_ID                   },
    {CLX_PKT_RX_REASON_IPV6_LEN_ERR,                IDS_CFG_EXCPT_EN_W0_IPV6_HDR_TRUNCATED_FIELD_ID         },
    {CLX_PKT_RX_REASON_PPPOE_SRV_UNKNOWN,           IDS_CFG_EXCPT_EN_W0_PPPOE_SRV_UNK_FIELD_ID              },
    {CLX_PKT_RX_REASON_PPPOE_HDR_ERR,               IDS_CFG_EXCPT_EN_W0_PPPOE_HDR_FIELD_ID                  },
    {CLX_PKT_RX_REASON_IP_TUNNEL_IPV4_ERR,          IDS_CFG_EXCPT_EN_W0_IP_TNL_IPV4_VER_FIELD_ID            },
    {CLX_PKT_RX_REASON_IP_TUNNEL_IPV6_ERR,          IDS_CFG_EXCPT_EN_W0_IP_TNL_IPV6_VER_FIELD_ID            },
    {CLX_PKT_RX_REASON_DECAP_NSH_TTL_1,             IDS_CFG_EXCPT_EN_W0_DECAP_NSH_TTL_FIELD_ID              }, /* S */
    {CLX_PKT_RX_REASON_TRANSIT_NSH_TTL_1,           IDS_CFG_EXCPT_EN_W0_TRANSIT_NSH_TTL_FIELD_ID            }, /* S */
    {CLX_PKT_RX_REASON_DOS_CHK,                     IDS_CFG_EXCPT_EN_W0_SDK_DOS_CHK_0_FIELD_ID              }, /* S */

    /* -------------------------------------------- 128 --------------------------------------------------------- */
    {CLX_PKT_RX_REASON_TRILL_LKP_MISS,              IEV_CFG_EXCPT_EN_W3_TRILL_UC_ADJ_FIELD_ID               },
    {CLX_PKT_RX_REASON_EGR_L3_MTU_FAIL,             IEV_CFG_EXCPT_EN_W3_L3_MTU_FIELD_ID                     }, /* L3 */
    {CLX_PKT_RX_REASON_ECMP_LKP_MISS,               IEV_CFG_EXCPT_EN_W3_NVO3_RSLT_ECMP_PATH_U_EP_L3_TYP_FIELD_ID},
    {CLX_PKT_RX_REASON_TUNNEL_INIT_LKP_MISS,        IEV_CFG_EXCPT_EN_W3_NVO3_ENCAP_IDX_INVLD_FIELD_ID       },
    {CLX_PKT_RX_REASON_TUNNEL_INIT_LKP_MISS,        IEV_CFG_EXCPT_EN_W3_NVO3_ENCAP_INVLD_FIELD_ID           },
    {CLX_PKT_RX_REASON_ECMP_LKP_MISS,               IEV_CFG_EXCPT_EN_W3_L3_ECMP_PATH_TYP_FIELD_ID           },
    {CLX_PKT_RX_REASON_L2_LKP_MISS,                 IEV_CFG_EXCPT_EN_W3_L2_UEID_INVLD_FIELD_ID              },
    {CLX_PKT_RX_REASON_ECMP_LKP_MISS,               IEV_CFG_EXCPT_EN_W3_L2_ECMP_PATH_TYP_FIELD_ID           },
    {CLX_PKT_RX_REASON_L3_LKP_MISS,                 IEV_CFG_EXCPT_EN_W3_L3_UEID_INVLD_FIELD_ID              },
    {CLX_PKT_RX_REASON_L2_SA_MISS,                  IEV_CFG_EXCPT_EN_W3_L2_SA_MISS_FIELD_ID                 },
    {CLX_PKT_RX_REASON_L2_SA_MOVE,                  IEV_CFG_EXCPT_EN_W3_L2_SA_MOVE_FIELD_ID                 },
    {CLX_PKT_RX_REASON_SA_LEARN_FAIL,               IEV_CFG_EXCPT_EN_W3_RSVD0_FIELD_ID                      },
    {CLX_PKT_RX_REASON_STACKING_LOOP,               IEV_CFG_EXCPT_EN_W3_STACKING_LOOP_FIELD_ID              },
    {CLX_PKT_RX_REASON_OTHERS,                      IEV_CFG_EXCPT_EN_W3_L2_SRC_SUPP_FIELD_ID                },
    {CLX_PKT_RX_REASON_NSH_LKP_MISS,                IEV_CFG_EXCPT_EN_W3_L25_NSH_MISS_FIELD_ID               },
    {CLX_PKT_RX_REASON_NSH_LKP_MISS,                IEV_CFG_EXCPT_EN_W3_RSLT_BNK_TYP_L25_NSH_FIELD_ID       },
    {CLX_PKT_RX_REASON_L2_LKP_MISS,                 IEV_CFG_EXCPT_EN_W3_RSLT_BNK_TYP_L2_INDIR_FIELD_ID      },
    {CLX_PKT_RX_REASON_L3_LKP_MISS,                 IEV_CFG_EXCPT_EN_W3_RSLT_BNK_TYP_L3_INDIR_FIELD_ID      },
    {CLX_PKT_RX_REASON_FLOW_LKP_MISS,               IEV_CFG_EXCPT_EN_W3_RSLT_BNK_TYP_FLW_FIELD_ID           },
    {CLX_PKT_RX_REASON_ACL_LKP_MISS,                IEV_CFG_EXCPT_EN_W3_FLW_ICIA_3X_INVLD_IDX_FIELD_ID      },
    {CLX_PKT_RX_REASON_STORM_CONTROL,               IEV_CFG_EXCPT_EN_W3_STM_CTL_FIELD_ID                    },
    {CLX_PKT_RX_REASON_STP_BLOCK,                   IEV_CFG_EXCPT_EN_W3_L2_TOPO_BLK_FIELD_ID                },
    {CLX_PKT_RX_REASON_IPSG_CHK,                    IEV_CFG_EXCPT_EN_W3_ARP_SRC_GUARD_FIELD_ID              },
    {CLX_PKT_RX_REASON_IPSG_CHK,                    IEV_CFG_EXCPT_EN_W3_L3_IPV4_SRC_GUARD_FIELD_ID          },
    {CLX_PKT_RX_REASON_IPSG_CHK,                    IEV_CFG_EXCPT_EN_W3_L3_IPV6_SRC_GUARD_FIELD_ID          },
    {CLX_PKT_RX_REASON_IPSG_CHK,                    IEV_CFG_EXCPT_EN_W3_L3_FCOE_SRC_GUARD_FIELD_ID          },
    {CLX_PKT_RX_REASON_TRILL_LKP_MISS,              IEV_CFG_EXCPT_EN_W3_TRILL_MC_ADJ_FIELD_ID               },
    {CLX_PKT_RX_REASON_TRILL_MRPF_CHECK_FAIL,       IEV_CFG_EXCPT_EN_W3_TRILL_MC_RPF_FIELD_ID               },
    {CLX_PKT_RX_REASON_FLOW_LKP_MISS,               IEV_CFG_EXCPT_EN_W3_RSLT_BNK_TYP_L4_FIELD_ID            },
    {CLX_PKT_RX_REASON_L2_LKP_MISS,                 IEV_CFG_EXCPT_EN_W3_RSLT_BNK_TYP_L2_FIELD_ID            },
    {CLX_PKT_RX_REASON_L3_LKP_MISS,                 IEV_CFG_EXCPT_EN_W3_RSLT_BNK_TYP_L3_FIELD_ID            },
    {CLX_PKT_RX_REASON_L2_LKP_MISS,                 IEV_CFG_EXCPT_EN_W3_L2_DA_TYP_FIELD_ID                  },

    /* -------------------------------------------- 160 --------------------------------------------------------- */
    {CLX_PKT_RX_REASON_L2_LKP_MISS,                 IEV_CFG_EXCPT_EN_W2_L2_SA_TYP_FIELD_ID                  },
    {CLX_PKT_RX_REASON_TRILL_LKP_MISS,              IEV_CFG_EXCPT_EN_W2_L25_MISS_FIELD_ID                   },
    {CLX_PKT_RX_REASON_TRILL_LKP_MISS,              IEV_CFG_EXCPT_EN_W2_L25_TYP_FIELD_ID                    },
    {CLX_PKT_RX_REASON_IPV4_HDR_OPTION,             IEV_CFG_EXCPT_EN_W2_L3_SW_FWD_IPV4_FIELD_ID             }, /* L3 */
    {CLX_PKT_RX_REASON_IPV6_HOP_BY_HOP_EXT_HDR,     IEV_CFG_EXCPT_EN_W2_L3_SW_FWD_IPV6_FIELD_ID             }, /* L3 */
    {CLX_PKT_RX_REASON_FCOE_IFR_TO_CPU,             IEV_CFG_EXCPT_EN_W2_L3_FCOE_EXT_UNK_FIELD_ID            },
    {CLX_PKT_RX_REASON_FCOE_LKP_MISS,               IEV_CFG_EXCPT_EN_W2_L3_FCOE_DID_MISS_FIELD_ID           },
    {CLX_PKT_RX_REASON_FCOE_LKP_MISS,               IEV_CFG_EXCPT_EN_W2_L3_FCOE_TYP_FIELD_ID                },
    {CLX_PKT_RX_REASON_FCOE_ZONING_FAIL,            IEV_CFG_EXCPT_EN_W2_L3_FCOE_ZONING_FIELD_ID             }, /* L3 */
    {CLX_PKT_RX_REASON_TTL_EXPIRE,                  IEV_CFG_EXCPT_EN_W2_L3_FCOE_TTL_FIELD_ID                }, /* L3 */
    {CLX_PKT_RX_REASON_L3_LKP_MISS,                 IEV_CFG_EXCPT_EN_W2_L3_DA_TYP_FIELD_ID                  },
    {CLX_PKT_RX_REASON_TTL_EXPIRE,                  IEV_CFG_EXCPT_EN_W2_L3_IPV4_TTL_0_FIELD_ID              }, /* L3 */
    {CLX_PKT_RX_REASON_TTL_EXPIRE,                  IEV_CFG_EXCPT_EN_W2_L3_IPV4_TTL_1_FIELD_ID              }, /* L3 */
    {CLX_PKT_RX_REASON_TTL_EXPIRE,                  IEV_CFG_EXCPT_EN_W2_L3_IPV6_TTL_0_FIELD_ID              }, /* L3 */
    {CLX_PKT_RX_REASON_TTL_EXPIRE,                  IEV_CFG_EXCPT_EN_W2_L3_IPV6_TTL_1_FIELD_ID              }, /* L3 */
    {CLX_PKT_RX_REASON_ICMP_REDIRECT,               IEV_CFG_EXCPT_EN_W2_L3_IPV4_ICMP_REDIR_FIELD_ID         }, /* L3 */
    {CLX_PKT_RX_REASON_ICMP_REDIRECT,               IEV_CFG_EXCPT_EN_W2_L3_IPV6_ICMP_REDIR_FIELD_ID         }, /* L3 */
    {CLX_PKT_RX_REASON_L3MC_RPF_CHECK,              IEV_CFG_EXCPT_EN_W2_L3_IPV4_MRPF_FIELD_ID               }, /* L3 */
    {CLX_PKT_RX_REASON_L3MC_RPF_CHECK,              IEV_CFG_EXCPT_EN_W2_L3_IPV6_MRPF_FIELD_ID               }, /* L3 */
    {CLX_PKT_RX_REASON_IPV4_MC_LKP_MISS,            IEV_CFG_EXCPT_EN_W2_L3_IPV4_MC_MISS_FIELD_ID            },
    {CLX_PKT_RX_REASON_IPV6_MC_LKP_MISS,            IEV_CFG_EXCPT_EN_W2_L3_IPV6_MC_MISS_FIELD_ID            },
    {CLX_PKT_RX_REASON_TTL_EXPIRE,                  IEV_CFG_EXCPT_EN_W2_L3_IPV4_MC_BRIDGED_CP_TTL_0_FIELD_ID},
    {CLX_PKT_RX_REASON_TTL_EXPIRE,                  IEV_CFG_EXCPT_EN_W2_L3_IPV6_MC_BRIDGED_CP_TTL_0_FIELD_ID},
    {CLX_PKT_RX_REASON_L3_LKP_MISS,                 IEV_CFG_EXCPT_EN_W2_L3_SA_TYP_FIELD_ID                  },
    {CLX_PKT_RX_REASON_URPF_CHECK_FAIL,             IEV_CFG_EXCPT_EN_W2_L3_IPV4_URPF_FIELD_ID               }, /* L3 */
    {CLX_PKT_RX_REASON_URPF_CHECK_FAIL,             IEV_CFG_EXCPT_EN_W2_L3_IPV6_URPF_FIELD_ID               }, /* L3 */
    {CLX_PKT_RX_REASON_FLOW_LKP_MISS,               IEV_CFG_EXCPT_EN_W2_PBR_FLW_TYP_FIELD_ID                },
    {CLX_PKT_RX_REASON_NSH_INVALID_PKT,             IEV_CFG_EXCPT_EN_W2_NSH_POP_LEN_GT_6_FIELD_ID           },
    {CLX_PKT_RX_REASON_NSH_INVALID_PKT,             IEV_CFG_EXCPT_EN_W2_NSH_POP_CL_INVLD_FIELD_ID           },
    {CLX_PKT_RX_REASON_NSH_INVALID_PKT,             IEV_CFG_EXCPT_EN_W2_NSH_POP_INVLD_IP_VER_FIELD_ID       },
    {CLX_PKT_RX_REASON_FCOE_CLASS_2_F,              IEV_CFG_EXCPT_EN_W2_PBR_DROP_FIELD_ID                   },
    {CLX_PKT_RX_REASON_HW_ERROR,                    IEV_CFG_EXCPT_EN_W2_ECC_FIELD_ID                        },

    /* -------------------------------------------- 192 --------------------------------------------------------- */
    {CLX_PKT_RX_REASON_OTHERS,                      IEV_CFG_EXCPT_EN_W1_PORT_ISO_FIELD_ID                   }, /* not used */
    {CLX_PKT_RX_REASON_OTHERS,                      IEV_CFG_EXCPT_EN_W1_LRN_CLS_FIELD_ID                    }, /* not used */
    {CLX_PKT_RX_REASON_PORT_MTR_DROP,               IEV_CFG_EXCPT_EN_W1_PORT_MTR_FIELD_ID                   },
    {CLX_PKT_RX_REASON_IGR_L3_MTU_FAIL,             IEV_CFG_EXCPT_EN_W1_L3_MTU_IGR_FIELD_ID                 },
    {CLX_PKT_RX_REASON_WECMP,                       IEV_CFG_EXCPT_EN_W1_WECMP_FIELD_ID                      },
    {CLX_PKT_RX_REASON_OTHERS,                      IEV_CFG_EXCPT_EN_W1_RSVD_0_FIELD_ID                     },
    {CLX_PKT_RX_REASON_OTHERS,                      IEV_CFG_EXCPT_EN_W1_RSVD_1_FIELD_ID                     },
    {CLX_PKT_RX_REASON_OTHERS,                      IEV_CFG_EXCPT_EN_W1_RSVD_2_FIELD_ID                     },
    {CLX_PKT_RX_REASON_OTHERS,                      IEV_CFG_EXCPT_EN_W1_RSVD_3_FIELD_ID                     },
    {CLX_PKT_RX_REASON_USR_DEFINE_0,                IEV_CFG_EXCPT_EN_W1_USER_DEFINED_0_FIELD_ID             }, /* S */
    {CLX_PKT_RX_REASON_USR_DEFINE_1,                IEV_CFG_EXCPT_EN_W1_USER_DEFINED_1_FIELD_ID             }, /* S */
    {CLX_PKT_RX_REASON_USR_DEFINE_2,                IEV_CFG_EXCPT_EN_W1_USER_DEFINED_2_FIELD_ID             }, /* S */
    {CLX_PKT_RX_REASON_USR_DEFINE_3,                IEV_CFG_EXCPT_EN_W1_USER_DEFINED_3_FIELD_ID             }, /* S */
    {CLX_PKT_RX_REASON_USR_DEFINE_4,                IEV_CFG_EXCPT_EN_W1_USER_DEFINED_4_FIELD_ID             }, /* S */
    {CLX_PKT_RX_REASON_USR_DEFINE_5,                IEV_CFG_EXCPT_EN_W1_USER_DEFINED_5_FIELD_ID             }, /* S */
    {CLX_PKT_RX_REASON_USR_DEFINE_6,                IEV_CFG_EXCPT_EN_W1_USER_DEFINED_6_FIELD_ID             }, /* S */
    {CLX_PKT_RX_REASON_USR_DEFINE_7,                IEV_CFG_EXCPT_EN_W1_USER_DEFINED_7_FIELD_ID             }, /* S */
    {CLX_PKT_RX_REASON_USR_DEFINE_8,                IEV_CFG_EXCPT_EN_W1_USER_DEFINED_8_FIELD_ID             }, /* S */
    {CLX_PKT_RX_REASON_USR_DEFINE_9,                IEV_CFG_EXCPT_EN_W1_USER_DEFINED_9_FIELD_ID             }, /* S */
    {CLX_PKT_RX_REASON_USR_DEFINE_10,               IEV_CFG_EXCPT_EN_W1_USER_DEFINED_10_FIELD_ID            }, /* S */
    {CLX_PKT_RX_REASON_USR_DEFINE_11,               IEV_CFG_EXCPT_EN_W1_USER_DEFINED_11_FIELD_ID            }, /* S */
    {CLX_PKT_RX_REASON_USR_DEFINE_12,               IEV_CFG_EXCPT_EN_W1_USER_DEFINED_12_FIELD_ID            }, /* S */
    {CLX_PKT_RX_REASON_USR_DEFINE_13,               IEV_CFG_EXCPT_EN_W1_USER_DEFINED_13_FIELD_ID            }, /* S */
    {CLX_PKT_RX_REASON_REDIRECT_TO_CPU_L2UC,        IEV_CFG_EXCPT_EN_W1_SDK_REDIRECT_TO_CPU_L2UC_FIELD_ID   }, /* S */
    {CLX_PKT_RX_REASON_REDIRECT_TO_CPU_L3UC,        IEV_CFG_EXCPT_EN_W1_SDK_REDIRECT_TO_CPU_L3UC_FIELD_ID   }, /* S */
    {CLX_PKT_RX_REASON_GRE_ERSPAN_TERM_LKP_MISS,    IEV_CFG_EXCPT_EN_W1_SDK_MIRROR_ERSPAN_MISS_FIELD_ID     }, /* S */
    {CLX_PKT_RX_REASON_1588_RX_PKT,                 IEV_CFG_EXCPT_EN_W1_SDK_1588_RX_FIELD_ID                }, /* S */
    {CLX_PKT_RX_REASON_VM_PDU,                      IEV_CFG_EXCPT_EN_W1_SDK_VM_BFD_FIELD_ID                 }, /* S */
    {CLX_PKT_RX_REASON_VM_L2_FDB_MISS,              IEV_CFG_EXCPT_EN_W1_SDK_VM_FDB_MISS_FIELD_ID            }, /* S */
    {CLX_PKT_RX_REASON_BFD_CTRL_PKT,                IEV_CFG_EXCPT_EN_W1_SDK_L3_BFD_FIELD_ID                 }, /* S */
    {CLX_PKT_RX_REASON_L3_LKP_MISS,                 IEV_CFG_EXCPT_EN_W1_SDK_L3UC_DA_MISS_FIELD_ID           }, /* S */
    {CLX_PKT_RX_REASON_PIM_REGISTER,                IEV_CFG_EXCPT_EN_W1_SDK_L3MC_PIM_REGISTER_FIELD_ID      }, /* S */

    /* -------------------------------------------- 224 --------------------------------------------------------- */
    {CLX_PKT_RX_REASON_CIA_0,                       IEV_CFG_EXCPT_EN_W0_SDK_ICIA_REDIRECT_0_FIELD_ID        }, /* S */
    {CLX_PKT_RX_REASON_CIA_1,                       IEV_CFG_EXCPT_EN_W0_SDK_ICIA_REDIRECT_1_FIELD_ID        }, /* S */
    {CLX_PKT_RX_REASON_CIA_2,                       IEV_CFG_EXCPT_EN_W0_SDK_ICIA_REDIRECT_2_FIELD_ID        }, /* S */
    {CLX_PKT_RX_REASON_CIA_3,                       IEV_CFG_EXCPT_EN_W0_SDK_ICIA_REDIRECT_3_FIELD_ID        }, /* S */
    {CLX_PKT_RX_REASON_CIA_4,                       IEV_CFG_EXCPT_EN_W0_SDK_ICIA_REDIRECT_4_FIELD_ID        }, /* S */
    {CLX_PKT_RX_REASON_CIA_5,                       IEV_CFG_EXCPT_EN_W0_SDK_ICIA_REDIRECT_5_FIELD_ID        }, /* S */
    {CLX_PKT_RX_REASON_CIA_6,                       IEV_CFG_EXCPT_EN_W0_SDK_ICIA_REDIRECT_6_FIELD_ID        }, /* S */
    {CLX_PKT_RX_REASON_CIA_7,                       IEV_CFG_EXCPT_EN_W0_SDK_ICIA_REDIRECT_7_FIELD_ID        }, /* S */
    {CLX_PKT_RX_REASON_FLEX_TUNNEL_0_CHK,           IEV_CFG_EXCPT_EN_W0_SDK_FLEX_DECAP_0_REASON_0_FIELD_ID  }, /* S */
    {CLX_PKT_RX_REASON_FLEX_TUNNEL_0_CHK,           IEV_CFG_EXCPT_EN_W0_SDK_FLEX_DECAP_0_REASON_1_FIELD_ID  }, /* S */
    {CLX_PKT_RX_REASON_FLEX_TUNNEL_0_CHK,           IEV_CFG_EXCPT_EN_W0_SDK_FLEX_DECAP_0_REASON_2_FIELD_ID  }, /* S */
    {CLX_PKT_RX_REASON_FLEX_TUNNEL_0_CHK,           IEV_CFG_EXCPT_EN_W0_SDK_FLEX_DECAP_0_REASON_3_FIELD_ID  }, /* S */
    {CLX_PKT_RX_REASON_FLEX_TUNNEL_0_CHK,           IEV_CFG_EXCPT_EN_W0_SDK_FLEX_DECAP_0_REASON_4_FIELD_ID  }, /* S */
    {CLX_PKT_RX_REASON_FLEX_TUNNEL_0_CHK,           IEV_CFG_EXCPT_EN_W0_SDK_FLEX_DECAP_0_REASON_5_FIELD_ID  }, /* S */
    {CLX_PKT_RX_REASON_FLEX_TUNNEL_1_CHK,           IEV_CFG_EXCPT_EN_W0_SDK_FLEX_DECAP_1_REASON_0_FIELD_ID  }, /* S */
    {CLX_PKT_RX_REASON_FLEX_TUNNEL_1_CHK,           IEV_CFG_EXCPT_EN_W0_SDK_FLEX_DECAP_1_REASON_1_FIELD_ID  }, /* S */
    {CLX_PKT_RX_REASON_FLEX_TUNNEL_1_CHK,           IEV_CFG_EXCPT_EN_W0_SDK_FLEX_DECAP_1_REASON_2_FIELD_ID  }, /* S */
    {CLX_PKT_RX_REASON_FLEX_TUNNEL_1_CHK,           IEV_CFG_EXCPT_EN_W0_SDK_FLEX_DECAP_1_REASON_3_FIELD_ID  }, /* S */
    {CLX_PKT_RX_REASON_FLEX_TUNNEL_1_CHK,           IEV_CFG_EXCPT_EN_W0_SDK_FLEX_DECAP_1_REASON_4_FIELD_ID  }, /* S */
    {CLX_PKT_RX_REASON_FLEX_TUNNEL_1_CHK,           IEV_CFG_EXCPT_EN_W0_SDK_FLEX_DECAP_1_REASON_5_FIELD_ID  }, /* S */
    {CLX_PKT_RX_REASON_FLEX_TUNNEL_2_CHK,           IEV_CFG_EXCPT_EN_W0_SDK_FLEX_DECAP_2_REASON_0_FIELD_ID  }, /* S */
    {CLX_PKT_RX_REASON_FLEX_TUNNEL_2_CHK,           IEV_CFG_EXCPT_EN_W0_SDK_FLEX_DECAP_2_REASON_1_FIELD_ID  }, /* S */
    {CLX_PKT_RX_REASON_FLEX_TUNNEL_2_CHK,           IEV_CFG_EXCPT_EN_W0_SDK_FLEX_DECAP_2_REASON_2_FIELD_ID  }, /* S */
    {CLX_PKT_RX_REASON_FLEX_TUNNEL_2_CHK,           IEV_CFG_EXCPT_EN_W0_SDK_FLEX_DECAP_2_REASON_3_FIELD_ID  }, /* S */
    {CLX_PKT_RX_REASON_FLEX_TUNNEL_2_CHK,           IEV_CFG_EXCPT_EN_W0_SDK_FLEX_DECAP_2_REASON_4_FIELD_ID  }, /* S */
    {CLX_PKT_RX_REASON_FLEX_TUNNEL_2_CHK,           IEV_CFG_EXCPT_EN_W0_SDK_FLEX_DECAP_2_REASON_5_FIELD_ID  }, /* S */
    {CLX_PKT_RX_REASON_FLEX_TUNNEL_3_CHK,           IEV_CFG_EXCPT_EN_W0_SDK_FLEX_DECAP_3_REASON_0_FIELD_ID  }, /* S */
    {CLX_PKT_RX_REASON_FLEX_TUNNEL_3_CHK,           IEV_CFG_EXCPT_EN_W0_SDK_FLEX_DECAP_3_REASON_1_FIELD_ID  }, /* S */
    {CLX_PKT_RX_REASON_FLEX_TUNNEL_3_CHK,           IEV_CFG_EXCPT_EN_W0_SDK_FLEX_DECAP_3_REASON_2_FIELD_ID  }, /* S */
    {CLX_PKT_RX_REASON_FLEX_TUNNEL_3_CHK,           IEV_CFG_EXCPT_EN_W0_SDK_FLEX_DECAP_3_REASON_3_FIELD_ID  }, /* S */
    {CLX_PKT_RX_REASON_FLEX_TUNNEL_3_CHK,           IEV_CFG_EXCPT_EN_W0_SDK_FLEX_DECAP_3_REASON_4_FIELD_ID  }, /* S */
    {CLX_PKT_RX_REASON_FLEX_TUNNEL_3_CHK,           IEV_CFG_EXCPT_EN_W0_SDK_FLEX_DECAP_3_REASON_5_FIELD_ID  }, /* S */
};

static HAL_LIGHTNING_PKT_REASON_MAP_IPP_L3_EXCPT_T        _hal_lightning_pkt_user_reason_to_ipp_l3_excpt[] =
{
    /* 0:
     * EXCPT_IEV_L3_FCOE_ZONING
     */
    {CLX_PKT_RX_REASON_FCOE_ZONING_FAIL,            HAL_LIGHTNING_PKT_IPP_L3_EXCPT_FCOE_ZONING        },
    /* 1:
     * EXCPT_IEV_L3_IPV4_URPF
     * EXCPT_IEV_L3_IPV4_MRPF
     * EXCPT_IEV_L3_IPV6_URPF
     * EXCPT_IEV_L3_IPV6_MRPF
     */
    {CLX_PKT_RX_REASON_URPF_CHECK_FAIL,             HAL_LIGHTNING_PKT_IPP_L3_EXCPT_RPF                },
    {CLX_PKT_RX_REASON_L3MC_RPF_CHECK,              HAL_LIGHTNING_PKT_IPP_L3_EXCPT_RPF    /* is_mc */ },
    /* 2:
     * EXCPT_IEV_L3_IPV4_ICMP_REDIR
     * EXCPT_IEV_L3_IPV6_ICMP_REDIR
     */
    {CLX_PKT_RX_REASON_ICMP_REDIRECT,               HAL_LIGHTNING_PKT_IPP_L3_EXCPT_ICMP_REDIR         },
    /* 3:
     * EXCPT_IEV_L3_SW_FWD_IPV4
     * EXCPT_IEV_L3_SW_FWD_IPV6
     */
    {CLX_PKT_RX_REASON_IPV4_HDR_OPTION,             HAL_LIGHTNING_PKT_IPP_L3_EXCPT_SW_FWD             },
    {CLX_PKT_RX_REASON_IPV6_HOP_BY_HOP_EXT_HDR,     HAL_LIGHTNING_PKT_IPP_L3_EXCPT_SW_FWD /* is_v6 */ },
    /* 4:
     * EXCPT_IEV_L3_MTU
     */
    {CLX_PKT_RX_REASON_EGR_L3_MTU_FAIL,             HAL_LIGHTNING_PKT_IPP_L3_EXCPT_MTU                },
    /* 5:
     * EXCPT_IEV_L3_FCOE_TTL
     * EXCPT_IEV_L3_IPV4_TTL_0
     * EXCPT_IEV_L3_IPV4_TTL_1
     * EXCPT_IEV_L3_IPV6_TTL_0
     * EXCPT_IEV_L3_IPV6_TTL_1
     */
    {CLX_PKT_RX_REASON_TTL_EXPIRE,                  HAL_LIGHTNING_PKT_IPP_L3_EXCPT_TTL                },
};

/* Note: the _hal_lightning_pkt_user_reason_to_epp_excpt table should be organized in a way that
 * we can use HW value as index for lookup of user reason. Any future modification should
 * consider this!!!
 */
static HAL_LIGHTNING_PKT_REASON_MAP_EPP_EXCPT_T      _hal_lightning_pkt_user_reason_to_epp_excpt[] =
{
    /* --------------------------------------- 0 --------------------------------------------------------------- */
    {CLX_PKT_RX_REASON_OTHERS,                     EME_CFG_EXCPT_EN_W1_RSVD_0_FIELD_ID                     },
    {CLX_PKT_RX_REASON_EX_PMOD_LIMIT,              EME_CFG_EXCPT_EN_W1_HDR_INCR_LCL_FIELD_ID               },
    {CLX_PKT_RX_REASON_PAR_ERR,                    EME_CFG_EXCPT_EN_W1_DECAP_HDR_MISS_FIELD_ID             },
    {CLX_PKT_RX_REASON_PAR_ERR,                    EME_CFG_EXCPT_EN_W1_DECAP_ACT_INVLD_FIELD_ID            },
    {CLX_PKT_RX_REASON_PAR_ERR,                    EME_CFG_EXCPT_EN_W1_DECAP_FLEX_INVLD_FIELD_ID           },
    {CLX_PKT_RX_REASON_MPLS_INVALID_PKT,           EME_CFG_EXCPT_EN_W1_MPLS_ELI_BOS_FIELD_ID               },
    {CLX_PKT_RX_REASON_MPLS_INVALID_PKT,           EME_CFG_EXCPT_EN_W1_MPLS_ELI_EL_NON_IP_FIELD_ID         },
    {CLX_PKT_RX_REASON_MPLS_INVALID_PKT,           EME_CFG_EXCPT_EN_W1_MPLS_POP_BEYOND_BOS_FIELD_ID        },
    {CLX_PKT_RX_REASON_MPLS_INVALID_PKT,           EME_CFG_EXCPT_EN_W1_MPLS_2ND_ELI_FIELD_ID               },
    {CLX_PKT_RX_REASON_MPLS_INVALID_PKT,           EME_CFG_EXCPT_EN_W1_PHP_POP_EXPOSE_NON_IP_FIELD_ID      },
    {CLX_PKT_RX_REASON_MPLS_INVALID_PKT,           EME_CFG_EXCPT_EN_W1_MPLS_ENTROPY_BOS_FIELD_ID           },
    {CLX_PKT_RX_REASON_MPLS_INVALID_PKT,           EME_CFG_EXCPT_EN_W1_MPLS_DECAP_EXPOSE_NON_IP_FIELD_ID   },
    {CLX_PKT_RX_REASON_TRILL_LKP_MISS,             EME_CFG_EXCPT_EN_W1_TRILL_TRANSIT_ADJ_IDX_INVLD_FIELD_ID},
    {CLX_PKT_RX_REASON_L3_LKP_MISS,                EME_CFG_EXCPT_EN_W1_ADJ_RSLT_BNK_INVLD_FIELD_ID         },
    {CLX_PKT_RX_REASON_L3_LKP_MISS,                EME_CFG_EXCPT_EN_W1_L3_ADJ_IDX_INVLD_FIELD_ID           },
    {CLX_PKT_RX_REASON_L2_HDR_MISS,                EME_CFG_EXCPT_EN_W1_L2_HDR_MISS_FIELD_ID                },
    {CLX_PKT_RX_REASON_EGR_L3_MTU_FAIL,            EME_CFG_EXCPT_EN_W1_L3_MTU_FIELD_ID                     },
    {CLX_PKT_RX_REASON_EGR_IPV4_TTL_1,             EME_CFG_EXCPT_EN_W1_L3_IPV4_TTL_1_FIELD_ID              },
    {CLX_PKT_RX_REASON_EGR_IPV6_TTL_1,             EME_CFG_EXCPT_EN_W1_L3_IPV6_TTL_1_FIELD_ID              },
    {CLX_PKT_RX_REASON_OTHERS,                     EME_CFG_EXCPT_EN_W1_SRC_SUPP_FIELD_ID                   },
    {CLX_PKT_RX_REASON_FLOW_LKP_MISS,              EME_CFG_EXCPT_EN_W1_FCM_RSLT_BNK_INVLD_FIELD_ID         },
    {CLX_PKT_RX_REASON_FLOW_LKP_MISS,              EME_CFG_EXCPT_EN_W1_L25_UC_TURN_MC_FIELD_ID             },
    {CLX_PKT_RX_REASON_STP_BLOCK,                  EME_CFG_EXCPT_EN_W1_L2_TOPO_BLK_FIELD_ID                },
    {CLX_PKT_RX_REASON_OTHERS,                     EME_CFG_EXCPT_EN_W1_ECIA_DROP_FIELD_ID                  },
    {CLX_PKT_RX_REASON_NSH_LKP_MISS,               EME_CFG_EXCPT_EN_W1_NSH_O_NSH_FIELD_ID                  },
    {CLX_PKT_RX_REASON_NSH_LKP_MISS,               EME_CFG_EXCPT_EN_W1_NSH_UNK_ETYP_FIELD_ID               },
    {CLX_PKT_RX_REASON_NSH_LKP_MISS,               EME_CFG_EXCPT_EN_W1_NSH_RSLT_BNK_INVLD_FIELD_ID         },
    {CLX_PKT_RX_REASON_NSH_LKP_MISS,               EME_CFG_EXCPT_EN_W1_NSH_O_TNL_INVLD_FIELD_ID            },
    {CLX_PKT_RX_REASON_NSH_LKP_MISS,               EME_CFG_EXCPT_EN_W1_NSH_NXT_PTR_FIELD_ID                },
    {CLX_PKT_RX_REASON_TUNNEL_INIT_LKP_MISS,       EME_CFG_EXCPT_EN_W1_IP_TNL_TYP_FIELD_ID                 },
    {CLX_PKT_RX_REASON_MPLS_LKP_MISS,              EME_CFG_EXCPT_EN_W1_MPLS_NXT_PTR_FIELD_ID               },
    {CLX_PKT_RX_REASON_MPLS_LKP_MISS,              EME_CFG_EXCPT_EN_W1_MPLS_O_UNK_IP_TNL_FIELD_ID          },

    /* --------------------------------------- 32 -------------------------------------------------------------- */
    {CLX_PKT_RX_REASON_TRILL_LKP_MISS,             EME_CFG_EXCPT_EN_W0_TRILL_ENCAP_FGL_FIELD_ID            },
    {CLX_PKT_RX_REASON_TRILL_LKP_MISS,             EME_CFG_EXCPT_EN_W0_TRILL_ENCAP_VL_FIELD_ID             },
    {CLX_PKT_RX_REASON_EGR_TUNNEL_MTU_FAIL,        EME_CFG_EXCPT_EN_W0_NVO3_L3_MTU_FIELD_ID                },
    {CLX_PKT_RX_REASON_OTHERS,                     EME_CFG_EXCPT_EN_W0_PORT_ISO_FIELD_ID                   },
    {CLX_PKT_RX_REASON_OTHERS,                     EME_CFG_EXCPT_EN_W0_FCM_TLV_TYP_ORDERS_FIELD_ID         },
    {CLX_PKT_RX_REASON_OTHERS,                     EME_CFG_EXCPT_EN_W0_FCM_TLV_BIDX_ASCEND_FIELD_ID        },
    {CLX_PKT_RX_REASON_OTHERS,                     EME_CFG_EXCPT_EN_W0_FCM_TLV_OOR_FIELD_ID                },
    {CLX_PKT_RX_REASON_OTHERS,                     EME_CFG_EXCPT_EN_W0_FCM_TLV_TOT_FIELD_ID                },
    {CLX_PKT_RX_REASON_OTHERS,                     EME_CFG_EXCPT_EN_W0_FCM_REWR_IDX_OVERLAP_FIELD_ID       },
    {CLX_PKT_RX_REASON_OTHERS,                     EME_CFG_EXCPT_EN_W0_FCM_TLV_TOT_4X_FIELD_ID             },
    {CLX_PKT_RX_REASON_OTHERS,                     EME_CFG_EXCPT_EN_W0_FCM_TLV_CHG_BLST_FIELD_ID           },
    {CLX_PKT_RX_REASON_OTHERS,                     EME_CFG_EXCPT_EN_W0_FCM_TLV_INS_BLST_FIELD_ID           },
    {CLX_PKT_RX_REASON_OTHERS,                     EME_CFG_EXCPT_EN_W0_SRV_IDX_INVLD_FIELD_ID              },
    {CLX_PKT_RX_REASON_OTHERS,                     EME_CFG_EXCPT_EN_W0_FCM_TLV_INS_DEL_OVERLAP_FIELD_ID    },
    {CLX_PKT_RX_REASON_OTHERS,                     EME_CFG_EXCPT_EN_W0_FCM_TLV_INS_INVLD_FIELD_ID          },
    {CLX_PKT_RX_REASON_OTHERS,                     EME_CFG_EXCPT_EN_W0_FCM_TLV_DEL_INVLD_FIELD_ID          },
    {CLX_PKT_RX_REASON_OTHERS,                     EME_CFG_EXCPT_EN_W0_RSVD_1_FIELD_ID                     },
    {CLX_PKT_RX_REASON_OTHERS,                     EME_CFG_EXCPT_EN_W0_RSVD_2_FIELD_ID                     },
    {CLX_PKT_RX_REASON_OTHERS,                     EME_CFG_EXCPT_EN_W0_RSVD_3_FIELD_ID                     },
    {CLX_PKT_RX_REASON_PPPOE_SRV_UNKNOWN,          EME_CFG_EXCPT_EN_W0_PPPOE_SRV_UNK_FIELD_ID              },
    {CLX_PKT_RX_REASON_PPPOE_ENCAP_ERR,            EME_CFG_EXCPT_EN_W0_PPPOE_ENCAP_FIELD_ID                },
    {CLX_PKT_RX_REASON_IOAM_NODE_LEN_INVALID_IPV6, EME_CFG_EXCPT_EN_W0_IOAM_NODELEN_MIS_ALGN_IPV6_FIELD_ID },
    {CLX_PKT_RX_REASON_IOAM_NODE_LEN_INVALID_GRE,  EME_CFG_EXCPT_EN_W0_IOAM_NODELEN_MIS_ALGN_GRE_FIELD_ID  },
    {CLX_PKT_RX_REASON_IOAM_NODE_LEN_INVALID_GPE,  EME_CFG_EXCPT_EN_W0_IOAM_NODELEN_MIS_ALGN_GPE_FIELD_ID  },
    {CLX_PKT_RX_REASON_OTHERS,                     EME_CFG_EXCPT_EN_W0_IOAM_DEL_FIELD_ID                   },
    {CLX_PKT_RX_REASON_OTHERS,                     EME_CFG_EXCPT_EN_W0_IFA_DEL_FIELD_ID                    },
    {CLX_PKT_RX_REASON_OTHERS,                     EME_CFG_EXCPT_EN_W0_RSVD_4_FIELD_ID                     },
    {CLX_PKT_RX_REASON_OTHERS,                     EME_CFG_EXCPT_EN_W0_RSVD_5_FIELD_ID                     },
    {CLX_PKT_RX_REASON_OTHERS,                     EME_CFG_EXCPT_EN_W0_RSVD_6_FIELD_ID                     },
    {CLX_PKT_RX_REASON_OTHERS,                     EME_CFG_EXCPT_EN_W0_RSVD_7_FIELD_ID                     },
    {CLX_PKT_RX_REASON_OTHERS,                     EME_CFG_EXCPT_EN_W0_RSVD_8_FIELD_ID                     },
    {CLX_PKT_RX_REASON_OTHERS,                     EME_CFG_EXCPT_EN_W0_RSVD_9_FIELD_ID                     }
};

/* Note: the _hal_lightning_pkt_user_reason_to_ipp_rsn table should be organized in a way that
 * we can use HW value as index for lookup of user reason. Any future modification should
 * consider this!!!
 */
static HAL_LIGHTNING_PKT_REASON_MAP_IPP_RSN_T             _hal_lightning_pkt_user_reason_to_ipp_rsn[] =
{
    /* MC */
    {CLX_PKT_RX_REASON_OTHERS,                      HAL_LIGHTNING_PKT_IPP_RSN_RSVD_0                            },
    {CLX_PKT_RX_REASON_MPLS_CTRL_PKT,               HAL_LIGHTNING_PKT_IPP_RSN_IDS_MPLS_MP_LSP_INNER_IP_LCL      },
    {CLX_PKT_RX_REASON_TUNNEL_TERM_LKP_MISS,        HAL_LIGHTNING_PKT_IPP_RSN_IDS_IP_MC_TNL_LCL_INTF_MISS       },
    {CLX_PKT_RX_REASON_IP_TUNNEL_CTRL_PKT,          HAL_LIGHTNING_PKT_IPP_RSN_IDS_IP_MC_TNL_GRE_ISIS            },
    {CLX_PKT_RX_REASON_IP_TUNNEL_CTRL_PKT,          HAL_LIGHTNING_PKT_IPP_RSN_IDS_IP_MC_TNL_GRE_KA              },
    {CLX_PKT_RX_REASON_IP_TUNNEL_INNER_MC_LCL,      HAL_LIGHTNING_PKT_IPP_RSN_IDS_IP_MC_TNL_INNER_IP_LCL        },
    {CLX_PKT_RX_REASON_TRILL_LKP_MISS,              HAL_LIGHTNING_PKT_IPP_RSN_IDS_TRILL_MC_LCL_INTF_MISS        },
    {CLX_PKT_RX_REASON_IPMC_TUNNEL_INNER_VLAN_MISS, HAL_LIGHTNING_PKT_IPP_RSN_IDS_INNER_SRV_1ST_MISS            },
    {CLX_PKT_RX_REASON_IPMC_TUNNEL_INNER_VLAN_MISS, HAL_LIGHTNING_PKT_IPP_RSN_IDS_INNER_SRV_2ND_MISS            },
    {CLX_PKT_RX_REASON_TTL_EXPIRE,                  HAL_LIGHTNING_PKT_IPP_RSN_IEV_IP_MC_TTL0                    },
    {CLX_PKT_RX_REASON_TTL_EXPIRE,                  HAL_LIGHTNING_PKT_IPP_RSN_IEV_IP_MC_TTL1                    },

    /* UC */
    {CLX_PKT_RX_REASON_OTHERS,                      HAL_LIGHTNING_PKT_IPP_RSN_RSVD_1                            },
    {CLX_PKT_RX_REASON_OTHERS,                      HAL_LIGHTNING_PKT_IPP_RSN_RSVD_2                            },
    {CLX_PKT_RX_REASON_TUNNEL_ECN_CU,               HAL_LIGHTNING_PKT_IPP_RSN_IDS_ECN                           },
    {CLX_PKT_RX_REASON_ICMP_REDIRECT,               HAL_LIGHTNING_PKT_IPP_RSN_IEV_ICMP_REDIR                    },
    {CLX_PKT_RX_REASON_ICMP_REDIRECT,               HAL_LIGHTNING_PKT_IPP_RSN_IEV_ICMP_REDIR_WITH_RSN_IDS_ECN   },
};

static HAL_LIGHTNING_PKT_REASON_MAP_IPP_COPY2CPU_T        _hal_lightning_pkt_user_reason_to_ipp_copy2cpu[] =
{
    {CLX_PKT_RX_REASON_CIA_0,                       HAL_LIGHTNING_PKT_IPP_COPY2CPU_ICIA_0                       },
    {CLX_PKT_RX_REASON_CIA_1,                       HAL_LIGHTNING_PKT_IPP_COPY2CPU_ICIA_1                       },
    {CLX_PKT_RX_REASON_CIA_2,                       HAL_LIGHTNING_PKT_IPP_COPY2CPU_ICIA_2                       },
    {CLX_PKT_RX_REASON_CIA_3,                       HAL_LIGHTNING_PKT_IPP_COPY2CPU_ICIA_3                       },
    {CLX_PKT_RX_REASON_CIA_4,                       HAL_LIGHTNING_PKT_IPP_COPY2CPU_ICIA_4                       },
    {CLX_PKT_RX_REASON_CIA_5,                       HAL_LIGHTNING_PKT_IPP_COPY2CPU_ICIA_5                       },
    {CLX_PKT_RX_REASON_COPY_TO_CPU_L2UC,            HAL_LIGHTNING_PKT_IPP_COPY2CPU_COPY_TO_CPU_L2UC             },
    {CLX_PKT_RX_REASON_COPY_TO_CPU_L3UC,            HAL_LIGHTNING_PKT_IPP_COPY2CPU_COPY_TO_CPU_L3UC             },
    {CLX_PKT_RX_REASON_IGR_PORT_SFLOW,              HAL_LIGHTNING_PKT_IPP_COPY2CPU_PORT_SFLOW                   },
    {CLX_PKT_RX_REASON_ICIA_SFLOW,                  HAL_LIGHTNING_PKT_IPP_COPY2CPU_ICIA_SFLOW                   },
    {CLX_PKT_RX_REASON_IGR_FLOW_SFLOW,              HAL_LIGHTNING_PKT_IPP_COPY2CPU_FLOW_SFLOW                   },
    {CLX_PKT_RX_REASON_L3MC_SPT_READY_UNSET,        HAL_LIGHTNING_PKT_IPP_COPY2CPU_L3MC_SPT_READY_UNSET         },
    {CLX_PKT_RX_REASON_COPY_TO_CPU_L2MC,            HAL_LIGHTNING_PKT_IPP_COPY2CPU_COPY_TO_CPU_L2MC             },
    {CLX_PKT_RX_REASON_COPY_TO_CPU_L3MC,            HAL_LIGHTNING_PKT_IPP_COPY2CPU_COPY_TO_CPU_L3MC             },
    {CLX_PKT_RX_REASON_USR_DEFINE_0,                HAL_LIGHTNING_PKT_IPP_COPY2CPU_USR_DEFINE_0                 },
    {CLX_PKT_RX_REASON_USR_DEFINE_1,                HAL_LIGHTNING_PKT_IPP_COPY2CPU_USR_DEFINE_1                 },
};

static HAL_LIGHTNING_PKT_REASON_MAP_EPP_COPY2CPU_T        _hal_lightning_pkt_user_reason_to_epp_copy2cpu[] =
{
    {CLX_PKT_RX_REASON_CIA_0,                       HAL_LIGHTNING_PKT_EPP_COPY2CPU_ECIA_0                       },
    {CLX_PKT_RX_REASON_CIA_1,                       HAL_LIGHTNING_PKT_EPP_COPY2CPU_ECIA_1                       },
    {CLX_PKT_RX_REASON_CIA_2,                       HAL_LIGHTNING_PKT_EPP_COPY2CPU_ECIA_2                       },
    {CLX_PKT_RX_REASON_CIA_3,                       HAL_LIGHTNING_PKT_EPP_COPY2CPU_ECIA_3                       },
    {CLX_PKT_RX_REASON_EGR_PORT_SFLOW,              HAL_LIGHTNING_PKT_EPP_COPY2CPU_PORT_SFLOW                   },
    {CLX_PKT_RX_REASON_ECIA_SFLOW,                  HAL_LIGHTNING_PKT_EPP_COPY2CPU_ECIA_SFLOW                   },
    {CLX_PKT_RX_REASON_EGR_SFLOW_HIGH_LATENCY,      HAL_LIGHTNING_PKT_EPP_COPY2CPU_SFLOW_HIGH_LATENCY           },
    /*                                              Reserve a reason for HAL_LIGHTNING_PKT_EPP_COPY2CPU_DTEL_IFA_SAMPLE  */
};
#endif