/*******************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of Hangzhou Clounix Technology Limited. (C) 2013-2021
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("CLOUNIX SOFTWARE")
*  RECEIVED FROM CLOUNIX AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. CLOUNIX EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES CLOUNIX PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE CLOUNIX SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. CLOUNIX SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY CLOUNIX SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND CLOUNIX'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE CLOUNIX SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT CLOUNIX'S OPTION, TO REVISE OR REPLACE THE CLOUNIX SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  CLOUNIX FOR SUCH CLOUNIX SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*******************************************************************************/

/* FILE NAME:  hal_dev.h
 * PURPOSE:
 *  Provide a list of device IDs.
 *
 * NOTES:
 */

#ifndef HAL_DEV_H
#define HAL_DEV_H

/* INCLUDE FILE DECLARATIONS
 */
/* NAMING CONSTANT DECLARATIONS
 */

#define HAL_DEVICE_ID_MASK          (0xFFFF)
#define HAL_DEVICE_MODE_MASK        (0xF)
#define HAL_DEVICE_MODE_OFFSET      (28)
#define HAL_DEVICE_GET_ID(__id__)   \
    (__id__ & HAL_DEVICE_ID_MASK)
#define HAL_DEVICE_GET_MODE(__id__) \
    ((__id__ >> HAL_DEVICE_MODE_OFFSET) & HAL_DEVICE_MODE_MASK)

#define HAL_CLX_VENDOR_ID           (0x0E8D)
#define HAL_CL_VENDOR_ID            (0x1D9F)

#define HAL_DEVICE_MODE_P           (0x1)

#define HAL_DEVICE_ID_CL3257        (0x3257)
#define HAL_DEVICE_ID_CL3258        (0x3258)

#define HAL_DEVICE_ID_CL8300        (0x8300) /* chip family */
#define HAL_DEVICE_ID_CL8363        (0x8363) /* 1.08T 1Bin */
#define HAL_DEVICE_ID_CL8365        (0x8365) /* 1.8T 1Bin */
#define HAL_DEVICE_ID_CL8366        (0x8366) /* 2.4T 1Bin */
#define HAL_DEVICE_ID_CL8367        (0x8367) /* 3.2T 1Bin */
#define HAL_DEVICE_ID_CL8368        (0x8368) /* 3.2T 2Bin */
#define HAL_DEVICE_ID_CL8369        (0x8369) /* 6.4T 2Bin */

#define HAL_DEVICE_ID_CL8500        (0x8500) /* chip family */
#define HAL_DEVICE_ID_CL8571        (0x8571) /* 3.2T 2Bin */
#define HAL_DEVICE_ID_CL8573        (0x8573) /* 3.2T 2Bin */
#define HAL_DEVICE_ID_CL8575        (0x8575) /* 4.0T 4Bin */
#define HAL_DEVICE_ID_CL8577        (0x8577) /* 6.4T 4Bin */
#define HAL_DEVICE_ID_CL8577P       (HAL_DEVICE_ID_CL8577 | (HAL_DEVICE_MODE_P << HAL_DEVICE_MODE_OFFSET))
#define HAL_DEVICE_ID_CL8578        (0x8578) /* 8.0T 4Bin */
#define HAL_DEVICE_ID_CL8579        (0x1111) /* 12.8T 4Bin */

#define HAL_DEVICE_ID_CL8700        (0x8700) /* chip family */
#define HAL_DEVICE_ID_CL8771        (0x8771) /* 3.2T 2Bin */
#define HAL_DEVICE_ID_CL8773        (0x8773) /* 3.2T 2Bin */
#define HAL_DEVICE_ID_CL8775        (0x8775) /* 4.0T 4Bin */
#define HAL_DEVICE_ID_CL8777        (0x8777) /* 6.4T 4Bin */
#define HAL_DEVICE_ID_CL8778        (0x8778) /* 8.0T 4Bin */

//TODO_FIXME_PORT
//#define HAL_DEVICE_ID_CL8779        (0x8779) /* 12.8T: 8*slice */
#define HAL_DEVICE_ID_CL8779        (0x8579) /* 12.8T: 8*slice */

#define HAL_REVISION_ID_E1          (0x01)
#define HAL_REVISION_ID_E2          (0x02)

#define HAL_INVALID_DEVICE_ID       (0xFFFFFFFF)

//EDK
#define HAL_CLX_EDK_VENDOR_ID       (0x1556)
#define HAL_DEVICE_ID_EDK1100       (0x1100)
#define HAL_DEVICE_ID_EDK1111       (0x1111)

#endif  /* #ifndef HAL_DEV_H */
