/*******************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of Hangzhou Clounix Technology Limited. (C) 2013-2021
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("CLOUNIX SOFTWARE")
*  RECEIVED FROM CLOUNIX AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. CLOUNIX EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES CLOUNIX PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE CLOUNIX SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. CLOUNIX SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY CLOUNIX SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND CLOUNIX'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE CLOUNIX SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT CLOUNIX'S OPTION, TO REVISE OR REPLACE THE CLOUNIX SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  CLOUNIX FOR SUCH CLOUNIX SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*******************************************************************************/

/* FILE NAME:  hal_pkt_rsrc_knl.h
 * PURPOSE:
 *      It provides hal pkt module API.
 * NOTES:
 *
 */

#ifndef HAL_PKT_RSRC_KNL_H
#define HAL_PKT_RSRC_KNL_H

/* INCLUDE FILE DECLARTIONS
 */
#include <clx_types.h>

/* NAMING CONSTANT DECLARATIONS
 */
/* Keep these values applied to different modules. */
#define HAL_PKT_IPP_EXCPT_NUM           (256)
#define HAL_PKT_EPP_EXCPT_NUM           (64)
#define HAL_PKT_IPP_L3_EXCPT_NUM        (6)
#define HAL_PKT_IPP_RSN_NUM             (16)
#define HAL_PKT_IPP_COPY2CPU_NUM        (16)
#define HAL_PKT_EPP_COPY2CPU_NUM        (8)

/* LT_IEV_CFG_EXCPT_EN_W1_SDK_REDIRECT_TO_CPU_L2UC_FIELD_ID */
#define HAL_PKT_IPP_EXCPT_IEV_SDK_REDIRECT_TO_CPU_L2UC      (192 + 23)

/* LT_IEV_CFG_EXCPT_EN_W1_SDK_REDIRECT_TO_CPU_L3UC_FIELD_ID */
#define HAL_PKT_IPP_EXCPT_IEV_SDK_REDIRECT_TO_CPU_L3UC      (192 + 24)

/* LT_IEV_CFG_EXCPT_EN_W1_SDK_L3UC_DA_MISS_FIELD_ID */
#define HAL_PKT_IPP_EXCPT_IEV_SDK_L3UC_DA_MISS              (192 + 30)

/* LT_IEV_CFG_EXCPT_EN_W1_SDK_L3MC_PIM_REGISTER_FIELD_ID */
#define HAL_PKT_IPP_EXCPT_IEV_SDK_L3MC_PIM_REGISTER         (192 + 31)

/* LT_IEV_CFG_EXCPT_EN_W0_SDK_FLEX_DECAP_0_REASON_0_FIELD_ID */
#define HAL_PKT_IPP_EXCPT_IEV_SDK_FLEX_DECAP_0_REASON_0     (224 + 8)

/* HW define offset
 * Module write IEV.cp_to_cpu_idx=1-3
 * Module write IEV_CFG_CP_TO_CPU_BIT_POS[offset + cp_to_cpu_idx - 1]
 */
#define HAL_PKT_IEV_CP_TO_CPU_BIT_POS_L2UC_DA   (0)
#define HAL_PKT_IEV_CP_TO_CPU_BIT_POS_L2MC_DA   (3)
#define HAL_PKT_IEV_CP_TO_CPU_BIT_POS_L2SA      (6)
#define HAL_PKT_IEV_CP_TO_CPU_BIT_POS_MPLS      (9)
#define HAL_PKT_IEV_CP_TO_CPU_BIT_POS_TRILL     (12)
#define HAL_PKT_IEV_CP_TO_CPU_BIT_POS_FCOE      (15)
#define HAL_PKT_IEV_CP_TO_CPU_BIT_POS_L3UC_DA   (18)
#define HAL_PKT_IEV_CP_TO_CPU_BIT_POS_L3UC_SA   (21)
#define HAL_PKT_IEV_CP_TO_CPU_BIT_POS_L3MC      (24)
#define HAL_PKT_IEV_CP_TO_CPU_BIT_POS_FLW_UC    (27)
#define HAL_PKT_IEV_CP_TO_CPU_BIT_POS_FLW_MC    (30)

/* capacities are the same between CL8360 and CL8570 */
#define HAL_PKT_IPP_EXCPT_BITMAP_SIZE    (CLX_BITMAP_SIZE(HAL_PKT_IPP_EXCPT_NUM))
#define HAL_PKT_IPP_L3_EXCPT_BITMAP_SIZE (CLX_BITMAP_SIZE(HAL_PKT_IPP_L3_EXCPT_NUM))
#define HAL_PKT_EPP_EXCPT_BITMAP_SIZE    (CLX_BITMAP_SIZE(HAL_PKT_EPP_EXCPT_NUM))
#define HAL_PKT_IPP_RSN_BITMAP_SIZE      (CLX_BITMAP_SIZE(HAL_PKT_IPP_RSN_NUM))
#define HAL_PKT_IPP_COPY2CPU_BITMAP_SIZE (CLX_BITMAP_SIZE(HAL_PKT_IPP_COPY2CPU_NUM))
#define HAL_PKT_EPP_COPY2CPU_BITMAP_SIZE (CLX_BITMAP_SIZE(HAL_PKT_EPP_COPY2CPU_NUM))

typedef UI32_T HAL_PKT_IPP_EXCPT_BITMAP_T[HAL_PKT_IPP_EXCPT_BITMAP_SIZE];
typedef UI32_T HAL_PKT_IPP_L3_EXCPT_BITMAP_T[HAL_PKT_IPP_L3_EXCPT_BITMAP_SIZE];
typedef UI32_T HAL_PKT_EPP_EXCPT_BITMAP_T[HAL_PKT_EPP_EXCPT_BITMAP_SIZE];
typedef UI32_T HAL_PKT_IPP_RSN_BITMAP_T[HAL_PKT_IPP_RSN_BITMAP_SIZE];
typedef UI32_T HAL_PKT_IPP_COPY2CPU_BITMAP_T[HAL_PKT_IPP_COPY2CPU_BITMAP_SIZE];
typedef UI32_T HAL_PKT_EPP_COPY2CPU_BITMAP_T[HAL_PKT_EPP_COPY2CPU_BITMAP_SIZE];

typedef struct
{
    /* excpt */
    HAL_PKT_IPP_EXCPT_BITMAP_T        ipp_excpt_bitmap;
    HAL_PKT_IPP_L3_EXCPT_BITMAP_T     ipp_l3_excpt_bitmap;
    HAL_PKT_EPP_EXCPT_BITMAP_T        epp_excpt_bitmap;

    /* cp */
    HAL_PKT_IPP_RSN_BITMAP_T          ipp_rsn_bitmap;
    HAL_PKT_IPP_COPY2CPU_BITMAP_T     ipp_copy2cpu_bitmap;
    HAL_PKT_EPP_COPY2CPU_BITMAP_T     epp_copy2cpu_bitmap;

} HAL_PKT_RX_REASON_BITMAP_T;

/* Control-to-CPU Decap Types */
typedef enum
{
    HAL_PKT_CTRL_TO_CPU_DECAP_TYPE_NONE = 0,
    HAL_PKT_CTRL_TO_CPU_DECAP_TYPE_TRILL,
    HAL_PKT_CTRL_TO_CPU_DECAP_TYPE_MPLS,
    HAL_PKT_CTRL_TO_CPU_DECAP_TYPE_GRE,
    HAL_PKT_CTRL_TO_CPU_DECAP_TYPE_VXLAN_GPE,
    HAL_PKT_CTRL_TO_CPU_DECAP_TYPE_VXLAN_BAS,
    HAL_PKT_CTRL_TO_CPU_DECAP_TYPE_RAW,
    HAL_PKT_CTRL_TO_CPU_DECAP_TYPE_FLEX,
    HAL_PKT_CTRL_TO_CPU_DECAP_TYPE_LAST
} HAL_PKT_CTRL_TO_CPU_DECAP_TYPE_T;

/* Control-to-CPU Action Types */
typedef enum
{
    HAL_PKT_CTRL_TO_CPU_ACTION_TYPE_NONE = 0,
    HAL_PKT_CTRL_TO_CPU_ACTION_TYPE_CPU_QUE,
    HAL_PKT_CTRL_TO_CPU_ACTION_TYPE_REDIR,
    HAL_PKT_CTRL_TO_CPU_ACTION_TYPE_REDIR_IF_FWD,
    HAL_PKT_CTRL_TO_CPU_ACTION_TYPE_CP2CPU_IF_FWD,
    HAL_PKT_CTRL_TO_CPU_ACTION_TYPE_SUPP_CPU,
    HAL_PKT_CTRL_TO_CPU_ACTION_TYPE_DROP_ALL,
    HAL_PKT_CTRL_TO_CPU_ACTION_TYPE_INVALID
} HAL_PKT_CTRL_TO_CPU_ACTION_TYPE_T;

/* Control-to-CPU Types */
typedef enum
{
    HAL_PKT_GET_REASON_BY_KET_QUEUE = 0,
    HAL_PKT_GET_REASON_BY_KET_LCL_CHIP_IDX,
    HAL_PKT_GET_REASON_BY_KET_RCL_CHIP_IDX,
    HAL_PKT_GET_REASON_BY_KET_LAST
} HAL_PKT_GET_REASON_BY_KET_T;

/* INTERNAL SUBPROGRAM SPECIFICATIONS
 */

#endif  /* End of HAL_PKT_RSRC_KNL_H */
