/*******************************************************************************
 *  Copyright Statement:
 *  --------------------
 *  This software and the information contained therein are protected by
 *  copyright and other intellectual property laws and terms herein is
 *  confidential. The software may not be copied and the information
 *  contained herein may not be used or disclosed except with the written
 *  permission of Clounix (Shanghai) Technology Limited. (C) 2020-2023
 *
 *  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 *  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("CLOUNIX SOFTWARE")
 *  RECEIVED FROM CLOUNIX AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
 *  AN "AS-IS" BASIS ONLY. CLOUNIX EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 *  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 *  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 *  NEITHER DOES CLOUNIX PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 *  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 *  SUPPLIED WITH THE CLOUNIX SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
 *  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. CLOUNIX SHALL ALSO
 *  NOT BE RESPONSIBLE FOR ANY CLOUNIX SOFTWARE RELEASES MADE TO BUYER'S
 *  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
 *
 *  BUYER'S SOLE AND EXCLUSIVE REMEDY AND CLOUNIX'S ENTIRE AND CUMULATIVE
 *  LIABILITY WITH RESPECT TO THE CLOUNIX SOFTWARE RELEASED HEREUNDER WILL BE,
 *  AT CLOUNIX'S OPTION, TO REVISE OR REPLACE THE CLOUNIX SOFTWARE AT ISSUE,
 *  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
 *  CLOUNIX FOR SUCH CLOUNIX SOFTWARE AT ISSUE.
 *
 *  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
 *  WITH THE LAWS OF THE PEOPLE'S REPUBLIC OF CHINA, EXCLUDING ITS CONFLICT OF
 *  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
 *  RELATED THERETO SHALL BE SETTLED BY LAWSUIT IN SHANGHAI,CHINA UNDER.
 *
 *******************************************************************************/

/* FILE NAME:  hal_pkt_rsrc_knl.h
 * PURPOSE:
 *      It provides hal pkt module API.
 * NOTES:
 *
 */

#ifndef HAL_PKT_RSRC_KNL_H
#define HAL_PKT_RSRC_KNL_H

/* INCLUDE FILE DECLARTIONS
 */
#include <clx_types.h>
#include <clx_error.h>
#include <clx_pkt.h>

/* NAMING CONSTANT DECLARATIONS
 */

/* Keep these values applied to different modules. */
#define HAL_PKT_IPP_EXCPT_NUM    (256)
#define HAL_PKT_EPP_EXCPT_NUM    (64)
#define HAL_PKT_IPP_L3_EXCPT_NUM (6)
#define HAL_PKT_IPP_RSN_NUM      (16)
#define HAL_PKT_IPP_COPY2CPU_NUM (16)
#define HAL_PKT_EPP_COPY2CPU_NUM (8)

/* capacities are the same between CL8360 and CL8570 */
#define HAL_PKT_IPP_EXCPT_BITMAP_SIZE    (CLX_BITMAP_SIZE(HAL_PKT_IPP_EXCPT_NUM))
#define HAL_PKT_IPP_L3_EXCPT_BITMAP_SIZE (CLX_BITMAP_SIZE(HAL_PKT_IPP_L3_EXCPT_NUM))
#define HAL_PKT_EPP_EXCPT_BITMAP_SIZE    (CLX_BITMAP_SIZE(HAL_PKT_EPP_EXCPT_NUM))
#define HAL_PKT_IPP_RSN_BITMAP_SIZE      (CLX_BITMAP_SIZE(HAL_PKT_IPP_RSN_NUM))
#define HAL_PKT_IPP_COPY2CPU_BITMAP_SIZE (CLX_BITMAP_SIZE(HAL_PKT_IPP_COPY2CPU_NUM))
#define HAL_PKT_EPP_COPY2CPU_BITMAP_SIZE (CLX_BITMAP_SIZE(HAL_PKT_EPP_COPY2CPU_NUM))

typedef UI32_T HAL_PKT_IPP_EXCPT_BITMAP_T[HAL_PKT_IPP_EXCPT_BITMAP_SIZE];
typedef UI32_T HAL_PKT_IPP_L3_EXCPT_BITMAP_T[HAL_PKT_IPP_L3_EXCPT_BITMAP_SIZE];
typedef UI32_T HAL_PKT_EPP_EXCPT_BITMAP_T[HAL_PKT_EPP_EXCPT_BITMAP_SIZE];
typedef UI32_T HAL_PKT_IPP_RSN_BITMAP_T[HAL_PKT_IPP_RSN_BITMAP_SIZE];
typedef UI32_T HAL_PKT_IPP_COPY2CPU_BITMAP_T[HAL_PKT_IPP_COPY2CPU_BITMAP_SIZE];
typedef UI32_T HAL_PKT_EPP_COPY2CPU_BITMAP_T[HAL_PKT_EPP_COPY2CPU_BITMAP_SIZE];

typedef struct {
    /* excpt */
    HAL_PKT_IPP_EXCPT_BITMAP_T ipp_excpt_bitmap;
    HAL_PKT_IPP_L3_EXCPT_BITMAP_T ipp_l3_excpt_bitmap;
    HAL_PKT_EPP_EXCPT_BITMAP_T epp_excpt_bitmap;

    /* cp */
    HAL_PKT_IPP_RSN_BITMAP_T ipp_rsn_bitmap;
    HAL_PKT_IPP_COPY2CPU_BITMAP_T ipp_copy2cpu_bitmap;
    HAL_PKT_EPP_COPY2CPU_BITMAP_T epp_copy2cpu_bitmap;
} HAL_PKT_RX_REASON_BITMAP_T;
#endif /* End of HAL_VLAN_H */
