#!/bin/bash
# This script load/unload clx kernel modules

### BEGIN INIT INFO
# Provides:          load-clx-modules
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:     S
# Default-Stop:      0 6
# Short-Description: Load clx kernel modules
### END INIT INFO
#set socket buffer max size limit to 100MB
RMEM_SIZE_SETTING=104857600

case "$1" in
start)
        echo -n "Load clx kernel modules... "

        RMEM_SIZE=`cat /proc/sys/net/core/rmem_max`
        if [ $RMEM_SIZE -lt $RMEM_SIZE_SETTING ]; then
            echo "$RMEM_SIZE_SETTING" > /proc/sys/net/core/rmem_max
        fi
        WMEM_SIZE=`cat /proc/sys/net/core/wmem_max`
        if [ $WMEM_SIZE -lt 25165824 ]; then
            echo "25165824" > /proc/sys/net/core/wmem_max
        fi

        modprobe clx_dev clx_dev_tc=7

        echo "done."
        ;;

stop)
        echo -n "Unload clx kernel modules... "

        rmmod clx_dev

        echo "done."
        ;;

force-reload|restart)
        echo "Not supported"
        ;;

*)
        echo "Usage: /etc/init.d/clx-modules {start|stop}"
        exit 1
        ;;
esac

exit 0

